#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.17929
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Lbk.Mobile.UI.Droid.Resource", IsApplication=true)]

namespace Lbk.Mobile.UI.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues ();
		}
		
		public static void UpdateIdValues()
		{
			AndroidClassLibrary.Resource.Drawable.monoandroidsplash = Lbk.Mobile.UI.Droid.Resource.Drawable.monoandroidsplash;
			AndroidClassLibrary.Resource.Layout.monoandroidsplash = Lbk.Mobile.UI.Droid.Resource.Layout.monoandroidsplash;
			AndroidClassLibrary.Resource.String.ApplicationName = Lbk.Mobile.UI.Droid.Resource.String.ApplicationName;
			AndroidClassLibrary.Resource.String.Hello = Lbk.Mobile.UI.Droid.Resource.String.Hello;
			AndroidClassLibrary.Resource.Style.Mono_Android_Theme_Splash = Lbk.Mobile.UI.Droid.Resource.Style.Mono_Android_Theme_Splash;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int MvxDropDownItemTemplate = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int MvxHttpSource = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxItemTemplate = 2130771969;
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int button_advise = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int button_contact = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int button_events = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int button_facebook = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int button_galery = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int button_history = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int button_menu = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int button_menuOfTheDay = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int button_quiz = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int button_reservation = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int button_rooms = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int button_videos = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Icon = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int monoandroidsplash = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Splash = 2130837518;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060001
			public const int MvxBindableListItemTagUnique = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int MvxBindingTagUnique = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int btnMenu = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int btnMenuOfTheDay = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int btnReservation = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int textView1 = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int textView2 = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int textView3 = 2131099655;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int monoandroidsplash = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Page_Home = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Page_Menu = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Page_MenuOfTheDay = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Page_Reservation = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int SplashScreen = 2130903045;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int HelloBoris = 2130968578;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBindableListView = new int[] {
					2130771969,
					2130771970};
			
			// aapt resource value: 1
			public const int MvxBindableListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxBindableListView_MvxItemTemplate = 0;
			
			public static int[] MvxBinding = new int[] {
					2130771968};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			public static int[] MvxHttpImageView = new int[] {
					2130771971};
			
			// aapt resource value: 0
			public const int MvxHttpImageView_MvxHttpSource = 0;
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
