#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18052
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Lbk.Mobile.UI.Droid.Resource", IsApplication=true)]

namespace Lbk.Mobile.UI.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			Lbk.Mobile.Plugin.DeviceIdentifier.Droid.Resource.String.ApplicationName = Lbk.Mobile.UI.Droid.Resource.String.ApplicationName;
			Lbk.Mobile.Plugin.DeviceIdentifier.Droid.Resource.String.Hello = Lbk.Mobile.UI.Droid.Resource.String.Hello;
			Lbk.Mobile.Plugin.DocumentViewer.Droid.Resource.String.ApplicationName = Lbk.Mobile.UI.Droid.Resource.String.ApplicationName;
			Lbk.Mobile.Plugin.DocumentViewer.Droid.Resource.String.Hello = Lbk.Mobile.UI.Droid.Resource.String.Hello;
			Lbk.Mobile.Plugin.Reachability.Droid.Resource.String.ApplicationName = Lbk.Mobile.UI.Droid.Resource.String.ApplicationName;
			Lbk.Mobile.Plugin.Reachability.Droid.Resource.String.Hello = Lbk.Mobile.UI.Droid.Resource.String.Hello;
			Lbk.Mobile.Plugin.Settings.Droid.Resource.String.ApplicationName = Lbk.Mobile.UI.Droid.Resource.String.ApplicationName;
			Lbk.Mobile.Plugin.Settings.Droid.Resource.String.Hello = Lbk.Mobile.UI.Droid.Resource.String.Hello;
			Lbk.Mobile.Plugin.WebVideo.Droid.Resource.String.ApplicationName = Lbk.Mobile.UI.Droid.Resource.String.ApplicationName;
			Lbk.Mobile.Plugin.WebVideo.Droid.Resource.String.Hello = Lbk.Mobile.UI.Droid.Resource.String.Hello;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.centered = Lbk.Mobile.UI.Droid.Resource.Attribute.centered;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.clipPadding = Lbk.Mobile.UI.Droid.Resource.Attribute.clipPadding;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.fadeDelay = Lbk.Mobile.UI.Droid.Resource.Attribute.fadeDelay;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.fadeLength = Lbk.Mobile.UI.Droid.Resource.Attribute.fadeLength;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.fades = Lbk.Mobile.UI.Droid.Resource.Attribute.fades;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.fillColor = Lbk.Mobile.UI.Droid.Resource.Attribute.fillColor;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.footerColor = Lbk.Mobile.UI.Droid.Resource.Attribute.footerColor;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.footerIndicatorHeight = Lbk.Mobile.UI.Droid.Resource.Attribute.footerIndicatorHeight;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.footerIndicatorStyle = Lbk.Mobile.UI.Droid.Resource.Attribute.footerIndicatorStyle;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.footerIndicatorUnderlinePadding = Lbk.Mobile.UI.Droid.Resource.Attribute.footerIndicatorUnderlinePadding;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.footerLineHeight = Lbk.Mobile.UI.Droid.Resource.Attribute.footerLineHeight;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.footerPadding = Lbk.Mobile.UI.Droid.Resource.Attribute.footerPadding;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.gapWidth = Lbk.Mobile.UI.Droid.Resource.Attribute.gapWidth;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.linePosition = Lbk.Mobile.UI.Droid.Resource.Attribute.linePosition;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.lineWidth = Lbk.Mobile.UI.Droid.Resource.Attribute.lineWidth;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.pageColor = Lbk.Mobile.UI.Droid.Resource.Attribute.pageColor;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.radius = Lbk.Mobile.UI.Droid.Resource.Attribute.radius;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.selectedBold = Lbk.Mobile.UI.Droid.Resource.Attribute.selectedBold;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.selectedColor = Lbk.Mobile.UI.Droid.Resource.Attribute.selectedColor;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.snap = Lbk.Mobile.UI.Droid.Resource.Attribute.snap;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.strokeColor = Lbk.Mobile.UI.Droid.Resource.Attribute.strokeColor;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.strokeWidth = Lbk.Mobile.UI.Droid.Resource.Attribute.strokeWidth;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.titlePadding = Lbk.Mobile.UI.Droid.Resource.Attribute.titlePadding;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.topPadding = Lbk.Mobile.UI.Droid.Resource.Attribute.topPadding;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.unselectedColor = Lbk.Mobile.UI.Droid.Resource.Attribute.unselectedColor;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.vpiCirclePageIndicatorStyle = Lbk.Mobile.UI.Droid.Resource.Attribute.vpiCirclePageIndicatorStyle;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.vpiIconPageIndicatorStyle = Lbk.Mobile.UI.Droid.Resource.Attribute.vpiIconPageIndicatorStyle;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.vpiLinePageIndicatorStyle = Lbk.Mobile.UI.Droid.Resource.Attribute.vpiLinePageIndicatorStyle;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.vpiTabPageIndicatorStyle = Lbk.Mobile.UI.Droid.Resource.Attribute.vpiTabPageIndicatorStyle;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.vpiTitlePageIndicatorStyle = Lbk.Mobile.UI.Droid.Resource.Attribute.vpiTitlePageIndicatorStyle;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.vpiUnderlinePageIndicatorStyle = Lbk.Mobile.UI.Droid.Resource.Attribute.vpiUnderlinePageIndicatorStyle;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Boolean.default_circle_indicator_centered = Lbk.Mobile.UI.Droid.Resource.Boolean.default_circle_indicator_centered;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Boolean.default_circle_indicator_snap = Lbk.Mobile.UI.Droid.Resource.Boolean.default_circle_indicator_snap;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Boolean.default_line_indicator_centered = Lbk.Mobile.UI.Droid.Resource.Boolean.default_line_indicator_centered;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Boolean.default_title_indicator_selected_bold = Lbk.Mobile.UI.Droid.Resource.Boolean.default_title_indicator_selected_bold;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Boolean.default_underline_indicator_fades = Lbk.Mobile.UI.Droid.Resource.Boolean.default_underline_indicator_fades;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.default_circle_indicator_fill_color = Lbk.Mobile.UI.Droid.Resource.Color.default_circle_indicator_fill_color;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.default_circle_indicator_page_color = Lbk.Mobile.UI.Droid.Resource.Color.default_circle_indicator_page_color;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.default_circle_indicator_stroke_color = Lbk.Mobile.UI.Droid.Resource.Color.default_circle_indicator_stroke_color;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.default_line_indicator_selected_color = Lbk.Mobile.UI.Droid.Resource.Color.default_line_indicator_selected_color;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.default_line_indicator_unselected_color = Lbk.Mobile.UI.Droid.Resource.Color.default_line_indicator_unselected_color;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.default_title_indicator_footer_color = Lbk.Mobile.UI.Droid.Resource.Color.default_title_indicator_footer_color;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.default_title_indicator_selected_color = Lbk.Mobile.UI.Droid.Resource.Color.default_title_indicator_selected_color;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.default_title_indicator_text_color = Lbk.Mobile.UI.Droid.Resource.Color.default_title_indicator_text_color;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.default_underline_indicator_selected_color = Lbk.Mobile.UI.Droid.Resource.Color.default_underline_indicator_selected_color;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__background_holo_dark = Lbk.Mobile.UI.Droid.Resource.Color.vpi__background_holo_dark;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__background_holo_light = Lbk.Mobile.UI.Droid.Resource.Color.vpi__background_holo_light;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__bright_foreground_disabled_holo_dark = Lbk.Mobile.UI.Droid.Resource.Color.vpi__bright_foreground_disabled_holo_dark;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__bright_foreground_disabled_holo_light = Lbk.Mobile.UI.Droid.Resource.Color.vpi__bright_foreground_disabled_holo_light;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__bright_foreground_holo_dark = Lbk.Mobile.UI.Droid.Resource.Color.vpi__bright_foreground_holo_dark;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__bright_foreground_holo_light = Lbk.Mobile.UI.Droid.Resource.Color.vpi__bright_foreground_holo_light;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__bright_foreground_inverse_holo_dark = Lbk.Mobile.UI.Droid.Resource.Color.vpi__bright_foreground_inverse_holo_dark;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__bright_foreground_inverse_holo_light = Lbk.Mobile.UI.Droid.Resource.Color.vpi__bright_foreground_inverse_holo_light;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__dark_theme = Lbk.Mobile.UI.Droid.Resource.Color.vpi__dark_theme;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__light_theme = Lbk.Mobile.UI.Droid.Resource.Color.vpi__light_theme;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_circle_indicator_radius = Lbk.Mobile.UI.Droid.Resource.Dimension.default_circle_indicator_radius;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_circle_indicator_stroke_width = Lbk.Mobile.UI.Droid.Resource.Dimension.default_circle_indicator_stroke_width;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_line_indicator_gap_width = Lbk.Mobile.UI.Droid.Resource.Dimension.default_line_indicator_gap_width;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_line_indicator_line_width = Lbk.Mobile.UI.Droid.Resource.Dimension.default_line_indicator_line_width;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_line_indicator_stroke_width = Lbk.Mobile.UI.Droid.Resource.Dimension.default_line_indicator_stroke_width;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_title_indicator_clip_padding = Lbk.Mobile.UI.Droid.Resource.Dimension.default_title_indicator_clip_padding;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_title_indicator_footer_indicator_height = Lbk.Mobile.UI.Droid.Resource.Dimension.default_title_indicator_footer_indicator_height;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_title_indicator_footer_indicator_underline_padding = Lbk.Mobile.UI.Droid.Resource.Dimension.default_title_indicator_footer_indicator_underline_padding;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_title_indicator_footer_line_height = Lbk.Mobile.UI.Droid.Resource.Dimension.default_title_indicator_footer_line_height;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_title_indicator_footer_padding = Lbk.Mobile.UI.Droid.Resource.Dimension.default_title_indicator_footer_padding;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_title_indicator_text_size = Lbk.Mobile.UI.Droid.Resource.Dimension.default_title_indicator_text_size;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_title_indicator_title_padding = Lbk.Mobile.UI.Droid.Resource.Dimension.default_title_indicator_title_padding;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_title_indicator_top_padding = Lbk.Mobile.UI.Droid.Resource.Dimension.default_title_indicator_top_padding;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Drawable.vpi__tab_indicator = Lbk.Mobile.UI.Droid.Resource.Drawable.vpi__tab_indicator;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Drawable.vpi__tab_selected_focused_holo = Lbk.Mobile.UI.Droid.Resource.Drawable.vpi__tab_selected_focused_holo;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Drawable.vpi__tab_selected_holo = Lbk.Mobile.UI.Droid.Resource.Drawable.vpi__tab_selected_holo;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Drawable.vpi__tab_selected_pressed_holo = Lbk.Mobile.UI.Droid.Resource.Drawable.vpi__tab_selected_pressed_holo;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Drawable.vpi__tab_unselected_focused_holo = Lbk.Mobile.UI.Droid.Resource.Drawable.vpi__tab_unselected_focused_holo;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Drawable.vpi__tab_unselected_holo = Lbk.Mobile.UI.Droid.Resource.Drawable.vpi__tab_unselected_holo;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Drawable.vpi__tab_unselected_pressed_holo = Lbk.Mobile.UI.Droid.Resource.Drawable.vpi__tab_unselected_pressed_holo;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Id.bottom = Lbk.Mobile.UI.Droid.Resource.Id.bottom;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Id.none = Lbk.Mobile.UI.Droid.Resource.Id.none;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Id.top = Lbk.Mobile.UI.Droid.Resource.Id.top;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Id.triangle = Lbk.Mobile.UI.Droid.Resource.Id.triangle;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Id.underline = Lbk.Mobile.UI.Droid.Resource.Id.underline;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Integer.default_circle_indicator_orientation = Lbk.Mobile.UI.Droid.Resource.Integer.default_circle_indicator_orientation;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Integer.default_title_indicator_footer_indicator_style = Lbk.Mobile.UI.Droid.Resource.Integer.default_title_indicator_footer_indicator_style;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Integer.default_title_indicator_line_position = Lbk.Mobile.UI.Droid.Resource.Integer.default_title_indicator_line_position;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Integer.default_underline_indicator_fade_delay = Lbk.Mobile.UI.Droid.Resource.Integer.default_underline_indicator_fade_delay;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Integer.default_underline_indicator_fade_length = Lbk.Mobile.UI.Droid.Resource.Integer.default_underline_indicator_fade_length;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Style.TextAppearance_TabPageIndicator = Lbk.Mobile.UI.Droid.Resource.Style.TextAppearance_TabPageIndicator;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Style.Theme_PageIndicatorDefaults = Lbk.Mobile.UI.Droid.Resource.Style.Theme_PageIndicatorDefaults;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Style.Widget = Lbk.Mobile.UI.Droid.Resource.Style.Widget;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Style.Widget_IconPageIndicator = Lbk.Mobile.UI.Droid.Resource.Style.Widget_IconPageIndicator;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Style.Widget_TabPageIndicator = Lbk.Mobile.UI.Droid.Resource.Style.Widget_TabPageIndicator;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator = Lbk.Mobile.UI.Droid.Resource.Styleable.CirclePageIndicator;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_android_background = Lbk.Mobile.UI.Droid.Resource.Styleable.CirclePageIndicator_android_background;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_android_orientation = Lbk.Mobile.UI.Droid.Resource.Styleable.CirclePageIndicator_android_orientation;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_centered = Lbk.Mobile.UI.Droid.Resource.Styleable.CirclePageIndicator_centered;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_fillColor = Lbk.Mobile.UI.Droid.Resource.Styleable.CirclePageIndicator_fillColor;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_pageColor = Lbk.Mobile.UI.Droid.Resource.Styleable.CirclePageIndicator_pageColor;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_radius = Lbk.Mobile.UI.Droid.Resource.Styleable.CirclePageIndicator_radius;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_snap = Lbk.Mobile.UI.Droid.Resource.Styleable.CirclePageIndicator_snap;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_strokeColor = Lbk.Mobile.UI.Droid.Resource.Styleable.CirclePageIndicator_strokeColor;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_strokeWidth = Lbk.Mobile.UI.Droid.Resource.Styleable.CirclePageIndicator_strokeWidth;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.LinePageIndicator = Lbk.Mobile.UI.Droid.Resource.Styleable.LinePageIndicator;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.LinePageIndicator_android_background = Lbk.Mobile.UI.Droid.Resource.Styleable.LinePageIndicator_android_background;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.LinePageIndicator_centered = Lbk.Mobile.UI.Droid.Resource.Styleable.LinePageIndicator_centered;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.LinePageIndicator_gapWidth = Lbk.Mobile.UI.Droid.Resource.Styleable.LinePageIndicator_gapWidth;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.LinePageIndicator_lineWidth = Lbk.Mobile.UI.Droid.Resource.Styleable.LinePageIndicator_lineWidth;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.LinePageIndicator_selectedColor = Lbk.Mobile.UI.Droid.Resource.Styleable.LinePageIndicator_selectedColor;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.LinePageIndicator_strokeWidth = Lbk.Mobile.UI.Droid.Resource.Styleable.LinePageIndicator_strokeWidth;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.LinePageIndicator_unselectedColor = Lbk.Mobile.UI.Droid.Resource.Styleable.LinePageIndicator_unselectedColor;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator = Lbk.Mobile.UI.Droid.Resource.Styleable.TitlePageIndicator;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_android_background = Lbk.Mobile.UI.Droid.Resource.Styleable.TitlePageIndicator_android_background;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_android_textColor = Lbk.Mobile.UI.Droid.Resource.Styleable.TitlePageIndicator_android_textColor;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_android_textSize = Lbk.Mobile.UI.Droid.Resource.Styleable.TitlePageIndicator_android_textSize;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_clipPadding = Lbk.Mobile.UI.Droid.Resource.Styleable.TitlePageIndicator_clipPadding;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_footerColor = Lbk.Mobile.UI.Droid.Resource.Styleable.TitlePageIndicator_footerColor;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_footerIndicatorHeight = Lbk.Mobile.UI.Droid.Resource.Styleable.TitlePageIndicator_footerIndicatorHeight;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_footerIndicatorStyle = Lbk.Mobile.UI.Droid.Resource.Styleable.TitlePageIndicator_footerIndicatorStyle;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_footerIndicatorUnderlinePadding = Lbk.Mobile.UI.Droid.Resource.Styleable.TitlePageIndicator_footerIndicatorUnderlinePadding;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_footerLineHeight = Lbk.Mobile.UI.Droid.Resource.Styleable.TitlePageIndicator_footerLineHeight;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_footerPadding = Lbk.Mobile.UI.Droid.Resource.Styleable.TitlePageIndicator_footerPadding;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_linePosition = Lbk.Mobile.UI.Droid.Resource.Styleable.TitlePageIndicator_linePosition;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_selectedBold = Lbk.Mobile.UI.Droid.Resource.Styleable.TitlePageIndicator_selectedBold;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_selectedColor = Lbk.Mobile.UI.Droid.Resource.Styleable.TitlePageIndicator_selectedColor;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_titlePadding = Lbk.Mobile.UI.Droid.Resource.Styleable.TitlePageIndicator_titlePadding;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_topPadding = Lbk.Mobile.UI.Droid.Resource.Styleable.TitlePageIndicator_topPadding;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.UnderlinePageIndicator = Lbk.Mobile.UI.Droid.Resource.Styleable.UnderlinePageIndicator;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.UnderlinePageIndicator_android_background = Lbk.Mobile.UI.Droid.Resource.Styleable.UnderlinePageIndicator_android_background;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.UnderlinePageIndicator_fadeDelay = Lbk.Mobile.UI.Droid.Resource.Styleable.UnderlinePageIndicator_fadeDelay;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.UnderlinePageIndicator_fadeLength = Lbk.Mobile.UI.Droid.Resource.Styleable.UnderlinePageIndicator_fadeLength;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.UnderlinePageIndicator_fades = Lbk.Mobile.UI.Droid.Resource.Styleable.UnderlinePageIndicator_fades;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.UnderlinePageIndicator_selectedColor = Lbk.Mobile.UI.Droid.Resource.Styleable.UnderlinePageIndicator_selectedColor;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.ViewPagerIndicator = Lbk.Mobile.UI.Droid.Resource.Styleable.ViewPagerIndicator;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.ViewPagerIndicator_vpiCirclePageIndicatorStyle = Lbk.Mobile.UI.Droid.Resource.Styleable.ViewPagerIndicator_vpiCirclePageIndicatorStyle;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.ViewPagerIndicator_vpiIconPageIndicatorStyle = Lbk.Mobile.UI.Droid.Resource.Styleable.ViewPagerIndicator_vpiIconPageIndicatorStyle;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.ViewPagerIndicator_vpiLinePageIndicatorStyle = Lbk.Mobile.UI.Droid.Resource.Styleable.ViewPagerIndicator_vpiLinePageIndicatorStyle;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.ViewPagerIndicator_vpiTabPageIndicatorStyle = Lbk.Mobile.UI.Droid.Resource.Styleable.ViewPagerIndicator_vpiTabPageIndicatorStyle;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.ViewPagerIndicator_vpiTitlePageIndicatorStyle = Lbk.Mobile.UI.Droid.Resource.Styleable.ViewPagerIndicator_vpiTitlePageIndicatorStyle;
			DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.ViewPagerIndicator_vpiUnderlinePageIndicatorStyle = Lbk.Mobile.UI.Droid.Resource.Styleable.ViewPagerIndicator_vpiUnderlinePageIndicatorStyle;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01001f
			public const int MvxBind = 2130771999;
			
			// aapt resource value: 0x7f010023
			public const int MvxDropDownItemTemplate = 2130772003;
			
			// aapt resource value: 0x7f010022
			public const int MvxItemTemplate = 2130772002;
			
			// aapt resource value: 0x7f010020
			public const int MvxLang = 2130772000;
			
			// aapt resource value: 0x7f010024
			public const int MvxSource = 2130772004;
			
			// aapt resource value: 0x7f010021
			public const int MvxTemplate = 2130772001;
			
			// aapt resource value: 0x7f010006
			public const int centered = 2130771974;
			
			// aapt resource value: 0x7f010011
			public const int clipPadding = 2130771985;
			
			// aapt resource value: 0x7f01001d
			public const int fadeDelay = 2130771997;
			
			// aapt resource value: 0x7f01001e
			public const int fadeLength = 2130771998;
			
			// aapt resource value: 0x7f01001c
			public const int fades = 2130771996;
			
			// aapt resource value: 0x7f01000a
			public const int fillColor = 2130771978;
			
			// aapt resource value: 0x7f010012
			public const int footerColor = 2130771986;
			
			// aapt resource value: 0x7f010015
			public const int footerIndicatorHeight = 2130771989;
			
			// aapt resource value: 0x7f010014
			public const int footerIndicatorStyle = 2130771988;
			
			// aapt resource value: 0x7f010016
			public const int footerIndicatorUnderlinePadding = 2130771990;
			
			// aapt resource value: 0x7f010013
			public const int footerLineHeight = 2130771987;
			
			// aapt resource value: 0x7f010017
			public const int footerPadding = 2130771991;
			
			// aapt resource value: 0x7f010010
			public const int gapWidth = 2130771984;
			
			// aapt resource value: 0x7f010018
			public const int linePosition = 2130771992;
			
			// aapt resource value: 0x7f01000f
			public const int lineWidth = 2130771983;
			
			// aapt resource value: 0x7f01000b
			public const int pageColor = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int radius = 2130771980;
			
			// aapt resource value: 0x7f010019
			public const int selectedBold = 2130771993;
			
			// aapt resource value: 0x7f010007
			public const int selectedColor = 2130771975;
			
			// aapt resource value: 0x7f01000d
			public const int snap = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int strokeColor = 2130771982;
			
			// aapt resource value: 0x7f010008
			public const int strokeWidth = 2130771976;
			
			// aapt resource value: 0x7f01001a
			public const int titlePadding = 2130771994;
			
			// aapt resource value: 0x7f01001b
			public const int topPadding = 2130771995;
			
			// aapt resource value: 0x7f010009
			public const int unselectedColor = 2130771977;
			
			// aapt resource value: 0x7f010000
			public const int vpiCirclePageIndicatorStyle = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int vpiIconPageIndicatorStyle = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int vpiLinePageIndicatorStyle = 2130771970;
			
			// aapt resource value: 0x7f010004
			public const int vpiTabPageIndicatorStyle = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int vpiTitlePageIndicatorStyle = 2130771971;
			
			// aapt resource value: 0x7f010005
			public const int vpiUnderlinePageIndicatorStyle = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f060000
			public const int default_circle_indicator_centered = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int default_circle_indicator_snap = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int default_line_indicator_centered = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int default_title_indicator_selected_bold = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int default_underline_indicator_fades = 2131099652;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050008
			public const int default_circle_indicator_fill_color = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int default_circle_indicator_page_color = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int default_circle_indicator_stroke_color = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int default_line_indicator_selected_color = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int default_line_indicator_unselected_color = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int default_title_indicator_footer_color = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int default_title_indicator_selected_color = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int default_title_indicator_text_color = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int default_underline_indicator_selected_color = 2131034128;
			
			// aapt resource value: 0x7f050013
			public const int header_outside = 2131034131;
			
			// aapt resource value: 0x7f050015
			public const int listseparator = 2131034133;
			
			// aapt resource value: 0x7f050012
			public const int text = 2131034130;
			
			// aapt resource value: 0x7f050011
			public const int transparent = 2131034129;
			
			// aapt resource value: 0x7f050000
			public const int vpi__background_holo_dark = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int vpi__background_holo_light = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int vpi__bright_foreground_disabled_holo_dark = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int vpi__bright_foreground_disabled_holo_light = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int vpi__bright_foreground_holo_dark = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int vpi__bright_foreground_holo_light = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int vpi__bright_foreground_inverse_holo_dark = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int vpi__bright_foreground_inverse_holo_light = 2131034119;
			
			// aapt resource value: 0x7f050016
			public const int vpi__dark_theme = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int vpi__light_theme = 2131034135;
			
			// aapt resource value: 0x7f050014
			public const int white = 2131034132;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f080000
			public const int default_circle_indicator_radius = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int default_circle_indicator_stroke_width = 2131230721;
			
			// aapt resource value: 0x7f080003
			public const int default_line_indicator_gap_width = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int default_line_indicator_line_width = 2131230722;
			
			// aapt resource value: 0x7f080004
			public const int default_line_indicator_stroke_width = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int default_title_indicator_clip_padding = 2131230725;
			
			// aapt resource value: 0x7f080007
			public const int default_title_indicator_footer_indicator_height = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int default_title_indicator_footer_indicator_underline_padding = 2131230728;
			
			// aapt resource value: 0x7f080006
			public const int default_title_indicator_footer_line_height = 2131230726;
			
			// aapt resource value: 0x7f080009
			public const int default_title_indicator_footer_padding = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int default_title_indicator_text_size = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int default_title_indicator_title_padding = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int default_title_indicator_top_padding = 2131230732;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Braueustueberl1 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Braueustueberl2 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_ = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_advise = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_events = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_facebook = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_galery = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_historie = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_kontakt = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_launcher = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_mail = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_map = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_phone = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_pulltorefresh_arrow = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_quiz = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_reservierung = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic_rooms = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic_speisekarte = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ic_tageskarte = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ic_videos = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int Icon = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int list_item_arrow = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int pull_to_refresh_header_background = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int raum_hg = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int runde_ecken = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int splashscreen = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int starkbierfest = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int thumb_bennosaal = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int thumb_braeustueberl = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int thumb_dachauerstube = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int thumb_festsaal = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int thumb_filserstube = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int thumb_galeriesaal = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int thumb_gartenanbau = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int thumb_loewenempore = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int thumb_loewenterasse = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int thumb_terrasse = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int thumb_turmstueberl = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int thumb_turmzimmer = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int vpi__tab_indicator = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int vpi__tab_selected_focused_holo = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int vpi__tab_selected_holo = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int vpi__tab_selected_pressed_holo = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int vpi__tab_unselected_focused_holo = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int vpi__tab_unselected_holo = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int vpi__tab_unselected_pressed_holo = 2130837550;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040015
			public const int ErrorImage = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int ErrorText1 = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int ErrorText2 = 2130968599;
			
			// aapt resource value: 0x7f040005
			public const int MvxBindingTagUnique = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int bottom = 2130968579;
			
			// aapt resource value: 0x7f040007
			public const int btn_event_book = 2130968583;
			
			// aapt resource value: 0x7f04000b
			public const int history_pager = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int history_pager_indicator = 2130968588;
			
			// aapt resource value: 0x7f040012
			public const int image_pager = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int image_pager_indicator = 2130968595;
			
			// aapt resource value: 0x7f040000
			public const int none = 2130968576;
			
			// aapt resource value: 0x7f04000e
			public const int pull_to_refresh_image = 2130968590;
			
			// aapt resource value: 0x7f040008
			public const int pull_to_refresh_layout = 2130968584;
			
			// aapt resource value: 0x7f04000d
			public const int pull_to_refresh_progress = 2130968589;
			
			// aapt resource value: 0x7f04000f
			public const int pull_to_refresh_text = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int pull_to_refresh_updated_at = 2130968592;
			
			// aapt resource value: 0x7f040009
			public const int refresh_lower_button = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int refresh_upper_button = 2130968586;
			
			// aapt resource value: 0x7f040011
			public const int textView1 = 2130968593;
			
			// aapt resource value: 0x7f040014
			public const int toast_layout_error_root = 2130968596;
			
			// aapt resource value: 0x7f040004
			public const int top = 2130968580;
			
			// aapt resource value: 0x7f040001
			public const int triangle = 2130968577;
			
			// aapt resource value: 0x7f040019
			public const int txtHeader = 2130968601;
			
			// aapt resource value: 0x7f040018
			public const int txtHeadline = 2130968600;
			
			// aapt resource value: 0x7f040002
			public const int underline = 2130968578;
			
			// aapt resource value: 0x7f040006
			public const int webView_booking = 2130968582;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public const int default_circle_indicator_orientation = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int default_title_indicator_footer_indicator_style = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int default_title_indicator_line_position = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int default_underline_indicator_fade_delay = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int default_underline_indicator_fade_length = 2131165188;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Event_Booking = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Event_List = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Event_ListItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Event_ListView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int History = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int History_Details = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Home = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Menu = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int pull_down_pull_to_refresh_list = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int pull_up_pull_to_refresh_list = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Reservation = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Room_Details = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Room_ImagePagerItem = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int Room_List = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int Room_ListItem = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int SplashScreen = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int ToastLayout_Error = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int TodaysMenu_List = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int TodaysMenu_ListItem = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int TodaysMenu_ListItem_Footer = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int TodaysMenu_ListItem_Header = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int TodaysMenu_ListView = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int Video_List = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int Video_ListItem = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int Video_ListView = 2130903064;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f0a0001
			public const int ApplicationName = 2131361793;
			
			// aapt resource value: 0x7f0a0000
			public const int Hello = 2131361792;
			
			// aapt resource value: 0x7f0a0002
			public const int app_name = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int menu_name = 2131361795;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090005
			public const int ProgressBarDialog = 2131296261;
			
			// aapt resource value: 0x7f090003
			public const int TextAppearance_TabPageIndicator = 2131296259;
			
			// aapt resource value: 0x7f090000
			public const int Theme_PageIndicatorDefaults = 2131296256;
			
			// aapt resource value: 0x7f090006
			public const int Theme_Splash = 2131296262;
			
			// aapt resource value: 0x7f090001
			public const int Widget = 2131296257;
			
			// aapt resource value: 0x7f090004
			public const int Widget_IconPageIndicator = 2131296260;
			
			// aapt resource value: 0x7f090002
			public const int Widget_TabPageIndicator = 2131296258;
			
			// aapt resource value: 0x7f090009
			public const int gericht = 2131296265;
			
			// aapt resource value: 0x7f090007
			public const int header_outside = 2131296263;
			
			// aapt resource value: 0x7f09000a
			public const int preis = 2131296266;
			
			// aapt resource value: 0x7f090008
			public const int text_outside = 2131296264;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CirclePageIndicator = new int[] {
					16842948,
					16842964,
					2130771974,
					2130771976,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982};
			
			// aapt resource value: 1
			public const int CirclePageIndicator_android_background = 1;
			
			// aapt resource value: 0
			public const int CirclePageIndicator_android_orientation = 0;
			
			// aapt resource value: 2
			public const int CirclePageIndicator_centered = 2;
			
			// aapt resource value: 4
			public const int CirclePageIndicator_fillColor = 4;
			
			// aapt resource value: 5
			public const int CirclePageIndicator_pageColor = 5;
			
			// aapt resource value: 6
			public const int CirclePageIndicator_radius = 6;
			
			// aapt resource value: 7
			public const int CirclePageIndicator_snap = 7;
			
			// aapt resource value: 8
			public const int CirclePageIndicator_strokeColor = 8;
			
			// aapt resource value: 3
			public const int CirclePageIndicator_strokeWidth = 3;
			
			public static int[] LinePageIndicator = new int[] {
					16842964,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771983,
					2130771984};
			
			// aapt resource value: 0
			public const int LinePageIndicator_android_background = 0;
			
			// aapt resource value: 1
			public const int LinePageIndicator_centered = 1;
			
			// aapt resource value: 6
			public const int LinePageIndicator_gapWidth = 6;
			
			// aapt resource value: 5
			public const int LinePageIndicator_lineWidth = 5;
			
			// aapt resource value: 2
			public const int LinePageIndicator_selectedColor = 2;
			
			// aapt resource value: 3
			public const int LinePageIndicator_strokeWidth = 3;
			
			// aapt resource value: 4
			public const int LinePageIndicator_unselectedColor = 4;
			
			public static int[] MvxBinding = new int[] {
					2130771999,
					2130772000};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130772001};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130772004};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130772002,
					2130772003};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			public static int[] TitlePageIndicator = new int[] {
					16842901,
					16842904,
					16842964,
					2130771975,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995};
			
			// aapt resource value: 2
			public const int TitlePageIndicator_android_background = 2;
			
			// aapt resource value: 1
			public const int TitlePageIndicator_android_textColor = 1;
			
			// aapt resource value: 0
			public const int TitlePageIndicator_android_textSize = 0;
			
			// aapt resource value: 4
			public const int TitlePageIndicator_clipPadding = 4;
			
			// aapt resource value: 5
			public const int TitlePageIndicator_footerColor = 5;
			
			// aapt resource value: 8
			public const int TitlePageIndicator_footerIndicatorHeight = 8;
			
			// aapt resource value: 7
			public const int TitlePageIndicator_footerIndicatorStyle = 7;
			
			// aapt resource value: 9
			public const int TitlePageIndicator_footerIndicatorUnderlinePadding = 9;
			
			// aapt resource value: 6
			public const int TitlePageIndicator_footerLineHeight = 6;
			
			// aapt resource value: 10
			public const int TitlePageIndicator_footerPadding = 10;
			
			// aapt resource value: 11
			public const int TitlePageIndicator_linePosition = 11;
			
			// aapt resource value: 12
			public const int TitlePageIndicator_selectedBold = 12;
			
			// aapt resource value: 3
			public const int TitlePageIndicator_selectedColor = 3;
			
			// aapt resource value: 13
			public const int TitlePageIndicator_titlePadding = 13;
			
			// aapt resource value: 14
			public const int TitlePageIndicator_topPadding = 14;
			
			public static int[] UnderlinePageIndicator = new int[] {
					16842964,
					2130771975,
					2130771996,
					2130771997,
					2130771998};
			
			// aapt resource value: 0
			public const int UnderlinePageIndicator_android_background = 0;
			
			// aapt resource value: 3
			public const int UnderlinePageIndicator_fadeDelay = 3;
			
			// aapt resource value: 4
			public const int UnderlinePageIndicator_fadeLength = 4;
			
			// aapt resource value: 2
			public const int UnderlinePageIndicator_fades = 2;
			
			// aapt resource value: 1
			public const int UnderlinePageIndicator_selectedColor = 1;
			
			public static int[] ViewPagerIndicator = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int ViewPagerIndicator_vpiCirclePageIndicatorStyle = 0;
			
			// aapt resource value: 1
			public const int ViewPagerIndicator_vpiIconPageIndicatorStyle = 1;
			
			// aapt resource value: 2
			public const int ViewPagerIndicator_vpiLinePageIndicatorStyle = 2;
			
			// aapt resource value: 4
			public const int ViewPagerIndicator_vpiTabPageIndicatorStyle = 4;
			
			// aapt resource value: 3
			public const int ViewPagerIndicator_vpiTitlePageIndicatorStyle = 3;
			
			// aapt resource value: 5
			public const int ViewPagerIndicator_vpiUnderlinePageIndicatorStyle = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
