#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18052
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Lbk.Mobile.UI.Android.Resource", IsApplication=true)]

namespace Lbk.Mobile.UI.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			Cirrious.MvvmCross.Dialog.Droid.Resource.Drawable.dialog_disclosure = Lbk.Mobile.UI.Android.Resource.Drawable.dialog_disclosure;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Drawable.dialog_expander_ic_minimized = Lbk.Mobile.UI.Android.Resource.Drawable.dialog_expander_ic_minimized;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Drawable.dialog_icon = Lbk.Mobile.UI.Android.Resource.Drawable.dialog_icon;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Drawable.dialog_spinner_default_holo_dark = Lbk.Mobile.UI.Android.Resource.Drawable.dialog_spinner_default_holo_dark;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Drawable.dialog_spinner_default_holo_light = Lbk.Mobile.UI.Android.Resource.Drawable.dialog_spinner_default_holo_light;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Id.dialog_BoolField = Lbk.Mobile.UI.Android.Resource.Id.dialog_BoolField;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Id.dialog_Button = Lbk.Mobile.UI.Android.Resource.Id.dialog_Button;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Id.dialog_DisclosureField = Lbk.Mobile.UI.Android.Resource.Id.dialog_DisclosureField;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Id.dialog_HtmlField = Lbk.Mobile.UI.Android.Resource.Id.dialog_HtmlField;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Id.dialog_ImageLeft = Lbk.Mobile.UI.Android.Resource.Id.dialog_ImageLeft;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Id.dialog_ImageRight = Lbk.Mobile.UI.Android.Resource.Id.dialog_ImageRight;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Id.dialog_LabelField = Lbk.Mobile.UI.Android.Resource.Id.dialog_LabelField;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Id.dialog_LabelPercentageField = Lbk.Mobile.UI.Android.Resource.Id.dialog_LabelPercentageField;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Id.dialog_LabelSubtextField = Lbk.Mobile.UI.Android.Resource.Id.dialog_LabelSubtextField;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Id.dialog_Panel = Lbk.Mobile.UI.Android.Resource.Id.dialog_Panel;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Id.dialog_RadioButtonList = Lbk.Mobile.UI.Android.Resource.Id.dialog_RadioButtonList;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Id.dialog_SliderField = Lbk.Mobile.UI.Android.Resource.Id.dialog_SliderField;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Id.dialog_Spinner = Lbk.Mobile.UI.Android.Resource.Id.dialog_Spinner;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Id.dialog_ValueField = Lbk.Mobile.UI.Android.Resource.Id.dialog_ValueField;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Id.iFormFieldValue = Lbk.Mobile.UI.Android.Resource.Id.iFormFieldValue;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_achievements = Lbk.Mobile.UI.Android.Resource.Layout.dialog_achievements;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_boolfieldleft = Lbk.Mobile.UI.Android.Resource.Layout.dialog_boolfieldleft;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_boolfieldright = Lbk.Mobile.UI.Android.Resource.Layout.dialog_boolfieldright;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_boolfieldsubleft = Lbk.Mobile.UI.Android.Resource.Layout.dialog_boolfieldsubleft;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_boolfieldsubright = Lbk.Mobile.UI.Android.Resource.Layout.dialog_boolfieldsubright;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_button = Lbk.Mobile.UI.Android.Resource.Layout.dialog_button;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_datefield = Lbk.Mobile.UI.Android.Resource.Layout.dialog_datefield;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_fieldsetlabel = Lbk.Mobile.UI.Android.Resource.Layout.dialog_fieldsetlabel;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_floatimage = Lbk.Mobile.UI.Android.Resource.Layout.dialog_floatimage;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_html = Lbk.Mobile.UI.Android.Resource.Layout.dialog_html;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_labeldisclosure = Lbk.Mobile.UI.Android.Resource.Layout.dialog_labeldisclosure;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_labelfieldbelow = Lbk.Mobile.UI.Android.Resource.Layout.dialog_labelfieldbelow;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_labelfieldright = Lbk.Mobile.UI.Android.Resource.Layout.dialog_labelfieldright;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_multiline_labelfieldbelow = Lbk.Mobile.UI.Android.Resource.Layout.dialog_multiline_labelfieldbelow;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_onofffieldright = Lbk.Mobile.UI.Android.Resource.Layout.dialog_onofffieldright;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_panel = Lbk.Mobile.UI.Android.Resource.Layout.dialog_panel;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_root = Lbk.Mobile.UI.Android.Resource.Layout.dialog_root;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_selectlist = Lbk.Mobile.UI.Android.Resource.Layout.dialog_selectlist;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_selectlistfield = Lbk.Mobile.UI.Android.Resource.Layout.dialog_selectlistfield;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_textarea = Lbk.Mobile.UI.Android.Resource.Layout.dialog_textarea;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_textfieldbelow = Lbk.Mobile.UI.Android.Resource.Layout.dialog_textfieldbelow;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_textfieldright = Lbk.Mobile.UI.Android.Resource.Layout.dialog_textfieldright;
			Lbk.Mobile.Plugin.DeviceIdentifier.Droid.Resource.String.ApplicationName = Lbk.Mobile.UI.Android.Resource.String.ApplicationName;
			Lbk.Mobile.Plugin.DeviceIdentifier.Droid.Resource.String.Hello = Lbk.Mobile.UI.Android.Resource.String.Hello;
			Lbk.Mobile.Plugin.Reachability.Droid.Resource.String.ApplicationName = Lbk.Mobile.UI.Android.Resource.String.ApplicationName;
			Lbk.Mobile.Plugin.Reachability.Droid.Resource.String.Hello = Lbk.Mobile.UI.Android.Resource.String.Hello;
			Lbk.Mobile.Plugin.Settings.Droid.Resource.String.ApplicationName = Lbk.Mobile.UI.Android.Resource.String.ApplicationName;
			Lbk.Mobile.Plugin.Settings.Droid.Resource.String.Hello = Lbk.Mobile.UI.Android.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010005
			public const int MvxSource = 2130771973;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050001
			public const int black = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int grey = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int icongrey = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int lightgrey = 2131034115;
			
			// aapt resource value: 0x7f050007
			public const int listseparator = 2131034119;
			
			// aapt resource value: 0x7f050002
			public const int mainText = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int transparent = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int white = 2131034117;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int button_advise = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int button_contact = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int button_events = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int button_facebook = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int button_galery = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int button_history = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int button_menu = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int button_menuOfTheDay = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int button_quiz = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int button_reservation = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int button_rooms = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int button_videos = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int dialog_disclosure = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int dialog_expander_ic_minimized = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int dialog_icon = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int dialog_spinner_default_holo_dark = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int dialog_spinner_default_holo_light = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic_pulltorefresh_arrow = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int icon = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int Icon_origin = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int pull_to_refresh_header_background = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int splash = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int splash_origin = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int thn_bennosaal = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int thn_braeustueberl = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int thn_dachauerstube = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int thn_festsaal = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int thn_filserstube = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int thn_galeriesaal = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int thn_gartenanbau = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int thn_loewenempore = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int thn_loewenterasse = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int thn_terrasse = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int thn_turmstueberl = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int thn_turmzimmer = 2130837539;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060023
			public const int ErrorImage = 2131099683;
			
			// aapt resource value: 0x7f060024
			public const int ErrorText1 = 2131099684;
			
			// aapt resource value: 0x7f060025
			public const int ErrorText2 = 2131099685;
			
			// aapt resource value: 0x7f060000
			public const int MvxBindingTagUnique = 2131099648;
			
			// aapt resource value: 0x7f060018
			public const int btnEvents = 2131099672;
			
			// aapt resource value: 0x7f060011
			public const int btnMenu = 2131099665;
			
			// aapt resource value: 0x7f060010
			public const int btnMenuOfTheDay = 2131099664;
			
			// aapt resource value: 0x7f060017
			public const int btnQuiz = 2131099671;
			
			// aapt resource value: 0x7f060012
			public const int btnReservation = 2131099666;
			
			// aapt resource value: 0x7f060016
			public const int btnRoom = 2131099670;
			
			// aapt resource value: 0x7f060005
			public const int dialog_BoolField = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int dialog_Button = 2131099654;
			
			// aapt resource value: 0x7f06000b
			public const int dialog_DisclosureField = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int dialog_HtmlField = 2131099658;
			
			// aapt resource value: 0x7f060008
			public const int dialog_ImageLeft = 2131099656;
			
			// aapt resource value: 0x7f060003
			public const int dialog_ImageRight = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int dialog_LabelField = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int dialog_LabelPercentageField = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int dialog_LabelSubtextField = 2131099650;
			
			// aapt resource value: 0x7f06000c
			public const int dialog_Panel = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int dialog_RadioButtonList = 2131099661;
			
			// aapt resource value: 0x7f060009
			public const int dialog_SliderField = 2131099657;
			
			// aapt resource value: 0x7f06000e
			public const int dialog_Spinner = 2131099662;
			
			// aapt resource value: 0x7f060007
			public const int dialog_ValueField = 2131099655;
			
			// aapt resource value: 0x7f06000f
			public const int iFormFieldValue = 2131099663;
			
			// aapt resource value: 0x7f06001e
			public const int pull_to_refresh_image = 2131099678;
			
			// aapt resource value: 0x7f060026
			public const int pull_to_refresh_layout = 2131099686;
			
			// aapt resource value: 0x7f06001d
			public const int pull_to_refresh_progress = 2131099677;
			
			// aapt resource value: 0x7f06001f
			public const int pull_to_refresh_text = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int pull_to_refresh_updated_at = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int refresh_lower_button = 2131099681;
			
			// aapt resource value: 0x7f06001c
			public const int refresh_upper_button = 2131099676;
			
			// aapt resource value: 0x7f060013
			public const int textView1 = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int textView2 = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int textView3 = 2131099669;
			
			// aapt resource value: 0x7f060022
			public const int toast_layout_error_root = 2131099682;
			
			// aapt resource value: 0x7f06001b
			public const int txtEvents = 2131099675;
			
			// aapt resource value: 0x7f060028
			public const int txtHeader = 2131099688;
			
			// aapt resource value: 0x7f060027
			public const int txtHeadline = 2131099687;
			
			// aapt resource value: 0x7f06001a
			public const int txtQuiz = 2131099674;
			
			// aapt resource value: 0x7f060019
			public const int txtRooms = 2131099673;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int dialog_achievements = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int dialog_boolfieldleft = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int dialog_boolfieldright = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int dialog_boolfieldsubleft = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int dialog_boolfieldsubright = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int dialog_button = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int dialog_datefield = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int dialog_fieldsetlabel = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int dialog_floatimage = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int dialog_html = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int dialog_labeldisclosure = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int dialog_labelfieldbelow = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int dialog_labelfieldright = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int dialog_multiline_labelfieldbelow = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int dialog_onofffieldright = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int dialog_panel = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int dialog_root = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int dialog_selectlist = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int dialog_selectlistfield = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int dialog_textarea = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int dialog_textfieldbelow = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int dialog_textfieldright = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int Home = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int Menu = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int pull_down_pull_to_refresh_list = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int pull_up_pull_to_refresh_list = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int Reservation = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int Room_List = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int Room_ListItem = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int SplashScreen = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int ToastLayout_Error = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public const int TodaysMenu = 2130903071;
			
			// aapt resource value: 0x7f030020
			public const int TodaysMenu_List = 2130903072;
			
			// aapt resource value: 0x7f030021
			public const int TodaysMenu_ListItem = 2130903073;
			
			// aapt resource value: 0x7f030022
			public const int TodaysMenu_ListItem_Footer = 2130903074;
			
			// aapt resource value: 0x7f030023
			public const int TodaysMenu_ListItem_Header = 2130903075;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Theme_Splash = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
