#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18052
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Lbk.Mobile.UI.Droid.Test.Resource", IsApplication=true)]

namespace Lbk.Mobile.UI.Droid.Test
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Cirrious.MvvmCross.Plugins.Network.Droid.Resource.String.ApplicationName = global::Lbk.Mobile.UI.Droid.Test.Resource.String.ApplicationName;
			global::Cirrious.MvvmCross.Plugins.Network.Droid.Resource.String.Hello = global::Lbk.Mobile.UI.Droid.Test.Resource.String.Hello;
			global::Lbk.Mobile.Plugin.AppSettings.Droid.Resource.String.ApplicationName = global::Lbk.Mobile.UI.Droid.Test.Resource.String.ApplicationName;
			global::Lbk.Mobile.Plugin.AppSettings.Droid.Resource.String.Hello = global::Lbk.Mobile.UI.Droid.Test.Resource.String.Hello;
			global::Lbk.Mobile.Plugin.DeviceIdentifier.Droid.Resource.String.ApplicationName = global::Lbk.Mobile.UI.Droid.Test.Resource.String.ApplicationName;
			global::Lbk.Mobile.Plugin.DeviceIdentifier.Droid.Resource.String.Hello = global::Lbk.Mobile.UI.Droid.Test.Resource.String.Hello;
			global::Lbk.Mobile.Plugin.DocumentViewer.Droid.Resource.String.ApplicationName = global::Lbk.Mobile.UI.Droid.Test.Resource.String.ApplicationName;
			global::Lbk.Mobile.Plugin.DocumentViewer.Droid.Resource.String.Hello = global::Lbk.Mobile.UI.Droid.Test.Resource.String.Hello;
			global::Lbk.Mobile.Plugin.Settings.Droid.Resource.String.ApplicationName = global::Lbk.Mobile.UI.Droid.Test.Resource.String.ApplicationName;
			global::Lbk.Mobile.Plugin.Settings.Droid.Resource.String.Hello = global::Lbk.Mobile.UI.Droid.Test.Resource.String.Hello;
			global::Lbk.Mobile.Plugin.UserInteraction.Droid.Resource.String.ApplicationName = global::Lbk.Mobile.UI.Droid.Test.Resource.String.ApplicationName;
			global::Lbk.Mobile.Plugin.UserInteraction.Droid.Resource.String.Hello = global::Lbk.Mobile.UI.Droid.Test.Resource.String.Hello;
			global::Lbk.Mobile.Plugin.WebVideo.Droid.Resource.String.ApplicationName = global::Lbk.Mobile.UI.Droid.Test.Resource.String.ApplicationName;
			global::Lbk.Mobile.Plugin.WebVideo.Droid.Resource.String.Hello = global::Lbk.Mobile.UI.Droid.Test.Resource.String.Hello;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.centered = global::Lbk.Mobile.UI.Droid.Test.Resource.Attribute.centered;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.clipPadding = global::Lbk.Mobile.UI.Droid.Test.Resource.Attribute.clipPadding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.fadeDelay = global::Lbk.Mobile.UI.Droid.Test.Resource.Attribute.fadeDelay;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.fadeLength = global::Lbk.Mobile.UI.Droid.Test.Resource.Attribute.fadeLength;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.fades = global::Lbk.Mobile.UI.Droid.Test.Resource.Attribute.fades;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.fillColor = global::Lbk.Mobile.UI.Droid.Test.Resource.Attribute.fillColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.footerColor = global::Lbk.Mobile.UI.Droid.Test.Resource.Attribute.footerColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.footerIndicatorHeight = global::Lbk.Mobile.UI.Droid.Test.Resource.Attribute.footerIndicatorHeight;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.footerIndicatorStyle = global::Lbk.Mobile.UI.Droid.Test.Resource.Attribute.footerIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.footerIndicatorUnderlinePadding = global::Lbk.Mobile.UI.Droid.Test.Resource.Attribute.footerIndicatorUnderlinePadding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.footerLineHeight = global::Lbk.Mobile.UI.Droid.Test.Resource.Attribute.footerLineHeight;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.footerPadding = global::Lbk.Mobile.UI.Droid.Test.Resource.Attribute.footerPadding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.gapWidth = global::Lbk.Mobile.UI.Droid.Test.Resource.Attribute.gapWidth;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.linePosition = global::Lbk.Mobile.UI.Droid.Test.Resource.Attribute.linePosition;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.lineWidth = global::Lbk.Mobile.UI.Droid.Test.Resource.Attribute.lineWidth;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.pageColor = global::Lbk.Mobile.UI.Droid.Test.Resource.Attribute.pageColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.radius = global::Lbk.Mobile.UI.Droid.Test.Resource.Attribute.radius;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.selectedBold = global::Lbk.Mobile.UI.Droid.Test.Resource.Attribute.selectedBold;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.selectedColor = global::Lbk.Mobile.UI.Droid.Test.Resource.Attribute.selectedColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.snap = global::Lbk.Mobile.UI.Droid.Test.Resource.Attribute.snap;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.strokeColor = global::Lbk.Mobile.UI.Droid.Test.Resource.Attribute.strokeColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.strokeWidth = global::Lbk.Mobile.UI.Droid.Test.Resource.Attribute.strokeWidth;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.titlePadding = global::Lbk.Mobile.UI.Droid.Test.Resource.Attribute.titlePadding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.topPadding = global::Lbk.Mobile.UI.Droid.Test.Resource.Attribute.topPadding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.unselectedColor = global::Lbk.Mobile.UI.Droid.Test.Resource.Attribute.unselectedColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.vpiCirclePageIndicatorStyle = global::Lbk.Mobile.UI.Droid.Test.Resource.Attribute.vpiCirclePageIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.vpiIconPageIndicatorStyle = global::Lbk.Mobile.UI.Droid.Test.Resource.Attribute.vpiIconPageIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.vpiLinePageIndicatorStyle = global::Lbk.Mobile.UI.Droid.Test.Resource.Attribute.vpiLinePageIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.vpiTabPageIndicatorStyle = global::Lbk.Mobile.UI.Droid.Test.Resource.Attribute.vpiTabPageIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.vpiTitlePageIndicatorStyle = global::Lbk.Mobile.UI.Droid.Test.Resource.Attribute.vpiTitlePageIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.vpiUnderlinePageIndicatorStyle = global::Lbk.Mobile.UI.Droid.Test.Resource.Attribute.vpiUnderlinePageIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Boolean.default_circle_indicator_centered = global::Lbk.Mobile.UI.Droid.Test.Resource.Boolean.default_circle_indicator_centered;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Boolean.default_circle_indicator_snap = global::Lbk.Mobile.UI.Droid.Test.Resource.Boolean.default_circle_indicator_snap;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Boolean.default_line_indicator_centered = global::Lbk.Mobile.UI.Droid.Test.Resource.Boolean.default_line_indicator_centered;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Boolean.default_title_indicator_selected_bold = global::Lbk.Mobile.UI.Droid.Test.Resource.Boolean.default_title_indicator_selected_bold;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Boolean.default_underline_indicator_fades = global::Lbk.Mobile.UI.Droid.Test.Resource.Boolean.default_underline_indicator_fades;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.default_circle_indicator_fill_color = global::Lbk.Mobile.UI.Droid.Test.Resource.Color.default_circle_indicator_fill_color;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.default_circle_indicator_page_color = global::Lbk.Mobile.UI.Droid.Test.Resource.Color.default_circle_indicator_page_color;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.default_circle_indicator_stroke_color = global::Lbk.Mobile.UI.Droid.Test.Resource.Color.default_circle_indicator_stroke_color;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.default_line_indicator_selected_color = global::Lbk.Mobile.UI.Droid.Test.Resource.Color.default_line_indicator_selected_color;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.default_line_indicator_unselected_color = global::Lbk.Mobile.UI.Droid.Test.Resource.Color.default_line_indicator_unselected_color;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.default_title_indicator_footer_color = global::Lbk.Mobile.UI.Droid.Test.Resource.Color.default_title_indicator_footer_color;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.default_title_indicator_selected_color = global::Lbk.Mobile.UI.Droid.Test.Resource.Color.default_title_indicator_selected_color;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.default_title_indicator_text_color = global::Lbk.Mobile.UI.Droid.Test.Resource.Color.default_title_indicator_text_color;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.default_underline_indicator_selected_color = global::Lbk.Mobile.UI.Droid.Test.Resource.Color.default_underline_indicator_selected_color;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__background_holo_dark = global::Lbk.Mobile.UI.Droid.Test.Resource.Color.vpi__background_holo_dark;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__background_holo_light = global::Lbk.Mobile.UI.Droid.Test.Resource.Color.vpi__background_holo_light;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__bright_foreground_disabled_holo_dark = global::Lbk.Mobile.UI.Droid.Test.Resource.Color.vpi__bright_foreground_disabled_holo_dark;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__bright_foreground_disabled_holo_light = global::Lbk.Mobile.UI.Droid.Test.Resource.Color.vpi__bright_foreground_disabled_holo_light;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__bright_foreground_holo_dark = global::Lbk.Mobile.UI.Droid.Test.Resource.Color.vpi__bright_foreground_holo_dark;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__bright_foreground_holo_light = global::Lbk.Mobile.UI.Droid.Test.Resource.Color.vpi__bright_foreground_holo_light;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__bright_foreground_inverse_holo_dark = global::Lbk.Mobile.UI.Droid.Test.Resource.Color.vpi__bright_foreground_inverse_holo_dark;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__bright_foreground_inverse_holo_light = global::Lbk.Mobile.UI.Droid.Test.Resource.Color.vpi__bright_foreground_inverse_holo_light;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__dark_theme = global::Lbk.Mobile.UI.Droid.Test.Resource.Color.vpi__dark_theme;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__light_theme = global::Lbk.Mobile.UI.Droid.Test.Resource.Color.vpi__light_theme;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_circle_indicator_radius = global::Lbk.Mobile.UI.Droid.Test.Resource.Dimension.default_circle_indicator_radius;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_circle_indicator_stroke_width = global::Lbk.Mobile.UI.Droid.Test.Resource.Dimension.default_circle_indicator_stroke_width;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_line_indicator_gap_width = global::Lbk.Mobile.UI.Droid.Test.Resource.Dimension.default_line_indicator_gap_width;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_line_indicator_line_width = global::Lbk.Mobile.UI.Droid.Test.Resource.Dimension.default_line_indicator_line_width;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_line_indicator_stroke_width = global::Lbk.Mobile.UI.Droid.Test.Resource.Dimension.default_line_indicator_stroke_width;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_title_indicator_clip_padding = global::Lbk.Mobile.UI.Droid.Test.Resource.Dimension.default_title_indicator_clip_padding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_title_indicator_footer_indicator_height = global::Lbk.Mobile.UI.Droid.Test.Resource.Dimension.default_title_indicator_footer_indicator_height;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_title_indicator_footer_indicator_underline_padding = global::Lbk.Mobile.UI.Droid.Test.Resource.Dimension.default_title_indicator_footer_indicator_underline_padding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_title_indicator_footer_line_height = global::Lbk.Mobile.UI.Droid.Test.Resource.Dimension.default_title_indicator_footer_line_height;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_title_indicator_footer_padding = global::Lbk.Mobile.UI.Droid.Test.Resource.Dimension.default_title_indicator_footer_padding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_title_indicator_text_size = global::Lbk.Mobile.UI.Droid.Test.Resource.Dimension.default_title_indicator_text_size;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_title_indicator_title_padding = global::Lbk.Mobile.UI.Droid.Test.Resource.Dimension.default_title_indicator_title_padding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_title_indicator_top_padding = global::Lbk.Mobile.UI.Droid.Test.Resource.Dimension.default_title_indicator_top_padding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Drawable.vpi__tab_indicator = global::Lbk.Mobile.UI.Droid.Test.Resource.Drawable.vpi__tab_indicator;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Drawable.vpi__tab_selected_focused_holo = global::Lbk.Mobile.UI.Droid.Test.Resource.Drawable.vpi__tab_selected_focused_holo;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Drawable.vpi__tab_selected_holo = global::Lbk.Mobile.UI.Droid.Test.Resource.Drawable.vpi__tab_selected_holo;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Drawable.vpi__tab_selected_pressed_holo = global::Lbk.Mobile.UI.Droid.Test.Resource.Drawable.vpi__tab_selected_pressed_holo;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Drawable.vpi__tab_unselected_focused_holo = global::Lbk.Mobile.UI.Droid.Test.Resource.Drawable.vpi__tab_unselected_focused_holo;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Drawable.vpi__tab_unselected_holo = global::Lbk.Mobile.UI.Droid.Test.Resource.Drawable.vpi__tab_unselected_holo;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Drawable.vpi__tab_unselected_pressed_holo = global::Lbk.Mobile.UI.Droid.Test.Resource.Drawable.vpi__tab_unselected_pressed_holo;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Id.bottom = global::Lbk.Mobile.UI.Droid.Test.Resource.Id.bottom;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Id.none = global::Lbk.Mobile.UI.Droid.Test.Resource.Id.none;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Id.top = global::Lbk.Mobile.UI.Droid.Test.Resource.Id.top;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Id.triangle = global::Lbk.Mobile.UI.Droid.Test.Resource.Id.triangle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Id.underline = global::Lbk.Mobile.UI.Droid.Test.Resource.Id.underline;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Integer.default_circle_indicator_orientation = global::Lbk.Mobile.UI.Droid.Test.Resource.Integer.default_circle_indicator_orientation;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Integer.default_title_indicator_footer_indicator_style = global::Lbk.Mobile.UI.Droid.Test.Resource.Integer.default_title_indicator_footer_indicator_style;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Integer.default_title_indicator_line_position = global::Lbk.Mobile.UI.Droid.Test.Resource.Integer.default_title_indicator_line_position;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Integer.default_underline_indicator_fade_delay = global::Lbk.Mobile.UI.Droid.Test.Resource.Integer.default_underline_indicator_fade_delay;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Integer.default_underline_indicator_fade_length = global::Lbk.Mobile.UI.Droid.Test.Resource.Integer.default_underline_indicator_fade_length;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Style.TextAppearance_TabPageIndicator = global::Lbk.Mobile.UI.Droid.Test.Resource.Style.TextAppearance_TabPageIndicator;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Style.Theme_PageIndicatorDefaults = global::Lbk.Mobile.UI.Droid.Test.Resource.Style.Theme_PageIndicatorDefaults;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Style.Widget = global::Lbk.Mobile.UI.Droid.Test.Resource.Style.Widget;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Style.Widget_IconPageIndicator = global::Lbk.Mobile.UI.Droid.Test.Resource.Style.Widget_IconPageIndicator;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Style.Widget_TabPageIndicator = global::Lbk.Mobile.UI.Droid.Test.Resource.Style.Widget_TabPageIndicator;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator = global::Lbk.Mobile.UI.Droid.Test.Resource.Styleable.CirclePageIndicator;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_android_background = global::Lbk.Mobile.UI.Droid.Test.Resource.Styleable.CirclePageIndicator_android_background;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_android_orientation = global::Lbk.Mobile.UI.Droid.Test.Resource.Styleable.CirclePageIndicator_android_orientation;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_centered = global::Lbk.Mobile.UI.Droid.Test.Resource.Styleable.CirclePageIndicator_centered;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_fillColor = global::Lbk.Mobile.UI.Droid.Test.Resource.Styleable.CirclePageIndicator_fillColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_pageColor = global::Lbk.Mobile.UI.Droid.Test.Resource.Styleable.CirclePageIndicator_pageColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_radius = global::Lbk.Mobile.UI.Droid.Test.Resource.Styleable.CirclePageIndicator_radius;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_snap = global::Lbk.Mobile.UI.Droid.Test.Resource.Styleable.CirclePageIndicator_snap;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_strokeColor = global::Lbk.Mobile.UI.Droid.Test.Resource.Styleable.CirclePageIndicator_strokeColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_strokeWidth = global::Lbk.Mobile.UI.Droid.Test.Resource.Styleable.CirclePageIndicator_strokeWidth;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.LinePageIndicator = global::Lbk.Mobile.UI.Droid.Test.Resource.Styleable.LinePageIndicator;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.LinePageIndicator_android_background = global::Lbk.Mobile.UI.Droid.Test.Resource.Styleable.LinePageIndicator_android_background;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.LinePageIndicator_centered = global::Lbk.Mobile.UI.Droid.Test.Resource.Styleable.LinePageIndicator_centered;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.LinePageIndicator_gapWidth = global::Lbk.Mobile.UI.Droid.Test.Resource.Styleable.LinePageIndicator_gapWidth;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.LinePageIndicator_lineWidth = global::Lbk.Mobile.UI.Droid.Test.Resource.Styleable.LinePageIndicator_lineWidth;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.LinePageIndicator_selectedColor = global::Lbk.Mobile.UI.Droid.Test.Resource.Styleable.LinePageIndicator_selectedColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.LinePageIndicator_strokeWidth = global::Lbk.Mobile.UI.Droid.Test.Resource.Styleable.LinePageIndicator_strokeWidth;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.LinePageIndicator_unselectedColor = global::Lbk.Mobile.UI.Droid.Test.Resource.Styleable.LinePageIndicator_unselectedColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator = global::Lbk.Mobile.UI.Droid.Test.Resource.Styleable.TitlePageIndicator;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_android_background = global::Lbk.Mobile.UI.Droid.Test.Resource.Styleable.TitlePageIndicator_android_background;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_android_textColor = global::Lbk.Mobile.UI.Droid.Test.Resource.Styleable.TitlePageIndicator_android_textColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_android_textSize = global::Lbk.Mobile.UI.Droid.Test.Resource.Styleable.TitlePageIndicator_android_textSize;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_clipPadding = global::Lbk.Mobile.UI.Droid.Test.Resource.Styleable.TitlePageIndicator_clipPadding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_footerColor = global::Lbk.Mobile.UI.Droid.Test.Resource.Styleable.TitlePageIndicator_footerColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_footerIndicatorHeight = global::Lbk.Mobile.UI.Droid.Test.Resource.Styleable.TitlePageIndicator_footerIndicatorHeight;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_footerIndicatorStyle = global::Lbk.Mobile.UI.Droid.Test.Resource.Styleable.TitlePageIndicator_footerIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_footerIndicatorUnderlinePadding = global::Lbk.Mobile.UI.Droid.Test.Resource.Styleable.TitlePageIndicator_footerIndicatorUnderlinePadding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_footerLineHeight = global::Lbk.Mobile.UI.Droid.Test.Resource.Styleable.TitlePageIndicator_footerLineHeight;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_footerPadding = global::Lbk.Mobile.UI.Droid.Test.Resource.Styleable.TitlePageIndicator_footerPadding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_linePosition = global::Lbk.Mobile.UI.Droid.Test.Resource.Styleable.TitlePageIndicator_linePosition;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_selectedBold = global::Lbk.Mobile.UI.Droid.Test.Resource.Styleable.TitlePageIndicator_selectedBold;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_selectedColor = global::Lbk.Mobile.UI.Droid.Test.Resource.Styleable.TitlePageIndicator_selectedColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_titlePadding = global::Lbk.Mobile.UI.Droid.Test.Resource.Styleable.TitlePageIndicator_titlePadding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_topPadding = global::Lbk.Mobile.UI.Droid.Test.Resource.Styleable.TitlePageIndicator_topPadding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.UnderlinePageIndicator = global::Lbk.Mobile.UI.Droid.Test.Resource.Styleable.UnderlinePageIndicator;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.UnderlinePageIndicator_android_background = global::Lbk.Mobile.UI.Droid.Test.Resource.Styleable.UnderlinePageIndicator_android_background;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.UnderlinePageIndicator_fadeDelay = global::Lbk.Mobile.UI.Droid.Test.Resource.Styleable.UnderlinePageIndicator_fadeDelay;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.UnderlinePageIndicator_fadeLength = global::Lbk.Mobile.UI.Droid.Test.Resource.Styleable.UnderlinePageIndicator_fadeLength;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.UnderlinePageIndicator_fades = global::Lbk.Mobile.UI.Droid.Test.Resource.Styleable.UnderlinePageIndicator_fades;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.UnderlinePageIndicator_selectedColor = global::Lbk.Mobile.UI.Droid.Test.Resource.Styleable.UnderlinePageIndicator_selectedColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.ViewPagerIndicator = global::Lbk.Mobile.UI.Droid.Test.Resource.Styleable.ViewPagerIndicator;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.ViewPagerIndicator_vpiCirclePageIndicatorStyle = global::Lbk.Mobile.UI.Droid.Test.Resource.Styleable.ViewPagerIndicator_vpiCirclePageIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.ViewPagerIndicator_vpiIconPageIndicatorStyle = global::Lbk.Mobile.UI.Droid.Test.Resource.Styleable.ViewPagerIndicator_vpiIconPageIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.ViewPagerIndicator_vpiLinePageIndicatorStyle = global::Lbk.Mobile.UI.Droid.Test.Resource.Styleable.ViewPagerIndicator_vpiLinePageIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.ViewPagerIndicator_vpiTabPageIndicatorStyle = global::Lbk.Mobile.UI.Droid.Test.Resource.Styleable.ViewPagerIndicator_vpiTabPageIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.ViewPagerIndicator_vpiTitlePageIndicatorStyle = global::Lbk.Mobile.UI.Droid.Test.Resource.Styleable.ViewPagerIndicator_vpiTitlePageIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.ViewPagerIndicator_vpiUnderlinePageIndicatorStyle = global::Lbk.Mobile.UI.Droid.Test.Resource.Styleable.ViewPagerIndicator_vpiUnderlinePageIndicatorStyle;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01002f
			public const int MvxBind = 2130772015;
			
			// aapt resource value: 0x7f010033
			public const int MvxDropDownItemTemplate = 2130772019;
			
			// aapt resource value: 0x7f010032
			public const int MvxItemTemplate = 2130772018;
			
			// aapt resource value: 0x7f010030
			public const int MvxLang = 2130772016;
			
			// aapt resource value: 0x7f010034
			public const int MvxSource = 2130772020;
			
			// aapt resource value: 0x7f010031
			public const int MvxTemplate = 2130772017;
			
			// aapt resource value: 0x7f010001
			public const int cameraBearing = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int cameraTargetLat = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cameraTargetLng = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int cameraTilt = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraZoom = 2130771973;
			
			// aapt resource value: 0x7f010014
			public const int centered = 2130771988;
			
			// aapt resource value: 0x7f01001f
			public const int clipPadding = 2130771999;
			
			// aapt resource value: 0x7f01002d
			public const int defaultImage = 2130772013;
			
			// aapt resource value: 0x7f01002b
			public const int fadeDelay = 2130772011;
			
			// aapt resource value: 0x7f01002c
			public const int fadeLength = 2130772012;
			
			// aapt resource value: 0x7f01002a
			public const int fades = 2130772010;
			
			// aapt resource value: 0x7f010018
			public const int fillColor = 2130771992;
			
			// aapt resource value: 0x7f010020
			public const int footerColor = 2130772000;
			
			// aapt resource value: 0x7f010023
			public const int footerIndicatorHeight = 2130772003;
			
			// aapt resource value: 0x7f010022
			public const int footerIndicatorStyle = 2130772002;
			
			// aapt resource value: 0x7f010024
			public const int footerIndicatorUnderlinePadding = 2130772004;
			
			// aapt resource value: 0x7f010021
			public const int footerLineHeight = 2130772001;
			
			// aapt resource value: 0x7f010025
			public const int footerPadding = 2130772005;
			
			// aapt resource value: 0x7f01001e
			public const int gapWidth = 2130771998;
			
			// aapt resource value: 0x7f010026
			public const int linePosition = 2130772006;
			
			// aapt resource value: 0x7f01001d
			public const int lineWidth = 2130771997;
			
			// aapt resource value: 0x7f010000
			public const int mapType = 2130771968;
			
			// aapt resource value: 0x7f010019
			public const int pageColor = 2130771993;
			
			// aapt resource value: 0x7f01001a
			public const int radius = 2130771994;
			
			// aapt resource value: 0x7f010027
			public const int selectedBold = 2130772007;
			
			// aapt resource value: 0x7f010015
			public const int selectedColor = 2130771989;
			
			// aapt resource value: 0x7f01001b
			public const int snap = 2130771995;
			
			// aapt resource value: 0x7f01001c
			public const int strokeColor = 2130771996;
			
			// aapt resource value: 0x7f010016
			public const int strokeWidth = 2130771990;
			
			// aapt resource value: 0x7f01002e
			public const int thumbnail = 2130772014;
			
			// aapt resource value: 0x7f010028
			public const int titlePadding = 2130772008;
			
			// aapt resource value: 0x7f010029
			public const int topPadding = 2130772009;
			
			// aapt resource value: 0x7f010006
			public const int uiCompass = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int uiRotateGestures = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int uiScrollGestures = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int uiTiltGestures = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiZoomControls = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiZoomGestures = 2130771979;
			
			// aapt resource value: 0x7f010017
			public const int unselectedColor = 2130771991;
			
			// aapt resource value: 0x7f01000c
			public const int useViewLifecycle = 2130771980;
			
			// aapt resource value: 0x7f01000e
			public const int vpiCirclePageIndicatorStyle = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int vpiIconPageIndicatorStyle = 2130771983;
			
			// aapt resource value: 0x7f010010
			public const int vpiLinePageIndicatorStyle = 2130771984;
			
			// aapt resource value: 0x7f010012
			public const int vpiTabPageIndicatorStyle = 2130771986;
			
			// aapt resource value: 0x7f010011
			public const int vpiTitlePageIndicatorStyle = 2130771985;
			
			// aapt resource value: 0x7f010013
			public const int vpiUnderlinePageIndicatorStyle = 2130771987;
			
			// aapt resource value: 0x7f01000d
			public const int zOrderOnTop = 2130771981;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f070000
			public const int default_circle_indicator_centered = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int default_circle_indicator_snap = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int default_line_indicator_centered = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int default_title_indicator_selected_bold = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int default_underline_indicator_fades = 2131165188;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f04001e
			public const int black = 2130968606;
			
			// aapt resource value: 0x7f040009
			public const int common_action_bar_splitter = 2130968585;
			
			// aapt resource value: 0x7f040000
			public const int common_signin_btn_dark_text_default = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int common_signin_btn_dark_text_disabled = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int common_signin_btn_dark_text_focused = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int common_signin_btn_dark_text_pressed = 2130968577;
			
			// aapt resource value: 0x7f040008
			public const int common_signin_btn_default_background = 2130968584;
			
			// aapt resource value: 0x7f040004
			public const int common_signin_btn_light_text_default = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int common_signin_btn_light_text_disabled = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int common_signin_btn_light_text_focused = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int common_signin_btn_light_text_pressed = 2130968581;
			
			// aapt resource value: 0x7f04003a
			public const int common_signin_btn_text_dark = 2130968634;
			
			// aapt resource value: 0x7f04003b
			public const int common_signin_btn_text_light = 2130968635;
			
			// aapt resource value: 0x7f040012
			public const int default_circle_indicator_fill_color = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int default_circle_indicator_page_color = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int default_circle_indicator_stroke_color = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int default_line_indicator_selected_color = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int default_line_indicator_unselected_color = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int default_title_indicator_footer_color = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int default_title_indicator_selected_color = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int default_title_indicator_text_color = 2130968601;
			
			// aapt resource value: 0x7f04001a
			public const int default_underline_indicator_selected_color = 2130968602;
			
			// aapt resource value: 0x7f040038
			public const int disabled_and_focused_border = 2130968632;
			
			// aapt resource value: 0x7f040037
			public const int disabled_and_focused_end = 2130968631;
			
			// aapt resource value: 0x7f040036
			public const int disabled_and_focused_start = 2130968630;
			
			// aapt resource value: 0x7f040039
			public const int disabled_and_focused_text = 2130968633;
			
			// aapt resource value: 0x7f040034
			public const int disabled_border = 2130968628;
			
			// aapt resource value: 0x7f040033
			public const int disabled_end = 2130968627;
			
			// aapt resource value: 0x7f040032
			public const int disabled_start = 2130968626;
			
			// aapt resource value: 0x7f040035
			public const int disabled_text = 2130968629;
			
			// aapt resource value: 0x7f040030
			public const int focused_border = 2130968624;
			
			// aapt resource value: 0x7f04002f
			public const int focused_end = 2130968623;
			
			// aapt resource value: 0x7f04002e
			public const int focused_start = 2130968622;
			
			// aapt resource value: 0x7f040031
			public const int focused_text = 2130968625;
			
			// aapt resource value: 0x7f04001f
			public const int grey = 2130968607;
			
			// aapt resource value: 0x7f040020
			public const int listseparator = 2130968608;
			
			// aapt resource value: 0x7f040028
			public const int normal_border = 2130968616;
			
			// aapt resource value: 0x7f040027
			public const int normal_end = 2130968615;
			
			// aapt resource value: 0x7f040026
			public const int normal_start = 2130968614;
			
			// aapt resource value: 0x7f040029
			public const int normal_text = 2130968617;
			
			// aapt resource value: 0x7f04002c
			public const int pressed_border = 2130968620;
			
			// aapt resource value: 0x7f04002b
			public const int pressed_end = 2130968619;
			
			// aapt resource value: 0x7f04002a
			public const int pressed_start = 2130968618;
			
			// aapt resource value: 0x7f04002d
			public const int pressed_text = 2130968621;
			
			// aapt resource value: 0x7f04001c
			public const int text = 2130968604;
			
			// aapt resource value: 0x7f04001b
			public const int transparent = 2130968603;
			
			// aapt resource value: 0x7f04000a
			public const int vpi__background_holo_dark = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int vpi__background_holo_light = 2130968587;
			
			// aapt resource value: 0x7f04000e
			public const int vpi__bright_foreground_disabled_holo_dark = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int vpi__bright_foreground_disabled_holo_light = 2130968591;
			
			// aapt resource value: 0x7f04000c
			public const int vpi__bright_foreground_holo_dark = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int vpi__bright_foreground_holo_light = 2130968589;
			
			// aapt resource value: 0x7f040010
			public const int vpi__bright_foreground_inverse_holo_dark = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int vpi__bright_foreground_inverse_holo_light = 2130968593;
			
			// aapt resource value: 0x7f04003c
			public const int vpi__dark_theme = 2130968636;
			
			// aapt resource value: 0x7f04003d
			public const int vpi__light_theme = 2130968637;
			
			// aapt resource value: 0x7f04001d
			public const int white = 2130968605;
			
			// aapt resource value: 0x7f040021
			public const int yellow1 = 2130968609;
			
			// aapt resource value: 0x7f040022
			public const int yellow2 = 2130968610;
			
			// aapt resource value: 0x7f040023
			public const int yellow3 = 2130968611;
			
			// aapt resource value: 0x7f040024
			public const int yellow4 = 2130968612;
			
			// aapt resource value: 0x7f040025
			public const int yellow5 = 2130968613;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f09000d
			public const int activity_horizontal_margin = 2131296269;
			
			// aapt resource value: 0x7f09000e
			public const int activity_vertical_margin = 2131296270;
			
			// aapt resource value: 0x7f09000f
			public const int btn_padding = 2131296271;
			
			// aapt resource value: 0x7f090013
			public const int button_height = 2131296275;
			
			// aapt resource value: 0x7f090010
			public const int corner_radius = 2131296272;
			
			// aapt resource value: 0x7f090000
			public const int default_circle_indicator_radius = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int default_circle_indicator_stroke_width = 2131296257;
			
			// aapt resource value: 0x7f090003
			public const int default_line_indicator_gap_width = 2131296259;
			
			// aapt resource value: 0x7f090002
			public const int default_line_indicator_line_width = 2131296258;
			
			// aapt resource value: 0x7f090004
			public const int default_line_indicator_stroke_width = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int default_title_indicator_clip_padding = 2131296261;
			
			// aapt resource value: 0x7f090007
			public const int default_title_indicator_footer_indicator_height = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int default_title_indicator_footer_indicator_underline_padding = 2131296264;
			
			// aapt resource value: 0x7f090006
			public const int default_title_indicator_footer_line_height = 2131296262;
			
			// aapt resource value: 0x7f090009
			public const int default_title_indicator_footer_padding = 2131296265;
			
			// aapt resource value: 0x7f09000a
			public const int default_title_indicator_text_size = 2131296266;
			
			// aapt resource value: 0x7f09000b
			public const int default_title_indicator_title_padding = 2131296267;
			
			// aapt resource value: 0x7f09000c
			public const int default_title_indicator_top_padding = 2131296268;
			
			// aapt resource value: 0x7f090014
			public const int half_button_height = 2131296276;
			
			// aapt resource value: 0x7f090012
			public const int layer_padding = 2131296274;
			
			// aapt resource value: 0x7f090011
			public const int stroke_width = 2131296273;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bg = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int btn_disabled = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int btn_disabled_and_focused = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int btn_focused = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int btn_lbk = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int btn_normal = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int btn_pressed = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int btn_selector_color = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int btn_selector_gradient = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_signin_btn_icon_dark = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_signin_btn_icon_disabled_dark = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_signin_btn_icon_disabled_focus_dark = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_signin_btn_icon_disabled_focus_light = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_signin_btn_icon_disabled_light = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_signin_btn_icon_focus_dark = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_signin_btn_icon_focus_light = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_signin_btn_icon_light = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_signin_btn_icon_normal_dark = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_signin_btn_icon_normal_light = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_signin_btn_icon_pressed_dark = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_signin_btn_icon_pressed_light = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_signin_btn_text_dark = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_signin_btn_text_disabled_dark = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_signin_btn_text_disabled_focus_dark = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_signin_btn_text_disabled_focus_light = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int common_signin_btn_text_disabled_light = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int common_signin_btn_text_focus_dark = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int common_signin_btn_text_focus_light = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int common_signin_btn_text_light = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int common_signin_btn_text_normal_dark = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int common_signin_btn_text_normal_light = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int common_signin_btn_text_pressed_dark = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int common_signin_btn_text_pressed_light = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int divider = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int divider_transparent = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int edittext_bg = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int ic_action_about = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int ic_action_event = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int ic_action_group = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int ic_action_map = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int ic_action_refresh = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int ic_action_time = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int ic_advise = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int ic_events = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int ic_facebook = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int ic_galery = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int ic_historie = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int ic_kontakt = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int ic_launcher = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int ic_mail = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int ic_map = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int ic_phone = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int ic_plusone_medium_off_client = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int ic_plusone_small_off_client = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int ic_plusone_standard_off_client = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int ic_plusone_tall_off_client = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int ic_pulltorefresh_arrow = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int ic_quiz = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int ic_reservierung = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int ic_rooms = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int ic_speisekarte = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int ic_tageskarte = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int ic_videos = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int Icon = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int list_item_bg = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int list_item_middle = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int list_rounded_item = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int list_rounded_item_top = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int picture_title_bg = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int runde_ecken = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int runde_ecken_bottom = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int runde_ecken_top = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int runde_ecken_top_grey = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int splash = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int vpi__tab_indicator = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int vpi__tab_selected_focused_holo = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int vpi__tab_selected_holo = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int vpi__tab_selected_pressed_holo = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int vpi__tab_unselected_focused_holo = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int vpi__tab_unselected_holo = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int vpi__tab_unselected_pressed_holo = 2130837585;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050009
			public const int MvxBindingTagUnique = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int MyButton = 2131034122;
			
			// aapt resource value: 0x7f05000c
			public const int action_imressum = 2131034124;
			
			// aapt resource value: 0x7f050007
			public const int bottom = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int hybrid = 2131034116;
			
			// aapt resource value: 0x7f05000d
			public const int map_actions = 2131034125;
			
			// aapt resource value: 0x7f050010
			public const int map_hybrid = 2131034128;
			
			// aapt resource value: 0x7f05000e
			public const int map_normal = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int map_satellite = 2131034127;
			
			// aapt resource value: 0x7f050000
			public const int none = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int normal = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int satellite = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int terrain = 2131034115;
			
			// aapt resource value: 0x7f050008
			public const int top = 2131034120;
			
			// aapt resource value: 0x7f050005
			public const int triangle = 2131034117;
			
			// aapt resource value: 0x7f05000b
			public const int txtHeadline = 2131034123;
			
			// aapt resource value: 0x7f050006
			public const int underline = 2131034118;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f080000
			public const int default_circle_indicator_orientation = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int default_title_indicator_footer_indicator_style = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int default_title_indicator_line_position = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int default_underline_indicator_fade_delay = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int default_underline_indicator_fade_length = 2131230724;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Home = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int SplashScreen = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int TodaysMenu_ListItem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int TodaysMenu_ListItem_Footer = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int TodaysMenu_ListItem_Header = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int TodaysMenu_ListView = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0b0000
			public const int contact_actions = 2131427328;
			
			// aapt resource value: 0x7f0b0001
			public const int map_actions = 2131427329;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f06001a
			public const int ApplicationName = 2131099674;
			
			// aapt resource value: 0x7f060019
			public const int Hello = 2131099673;
			
			// aapt resource value: 0x7f06001b
			public const int app_name = 2131099675;
			
			// aapt resource value: 0x7f060014
			public const int auth_client_needs_enabling_title = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int auth_client_needs_installation_title = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int auth_client_needs_update_title = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int auth_client_play_services_err_notification_msg = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int auth_client_requested_by_msg = 2131099672;
			
			// aapt resource value: 0x7f060013
			public const int auth_client_using_bad_version_title = 2131099667;
			
			// aapt resource value: 0x7f060006
			public const int common_google_play_services_enable_button = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int common_google_play_services_enable_text = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int common_google_play_services_enable_title = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int common_google_play_services_install_button = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int common_google_play_services_install_text_phone = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int common_google_play_services_install_text_tablet = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int common_google_play_services_install_title = 2131099648;
			
			// aapt resource value: 0x7f06000c
			public const int common_google_play_services_invalid_account_text = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int common_google_play_services_invalid_account_title = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int common_google_play_services_network_error_text = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int common_google_play_services_network_error_title = 2131099657;
			
			// aapt resource value: 0x7f06000d
			public const int common_google_play_services_unknown_issue = 2131099661;
			
			// aapt resource value: 0x7f06000f
			public const int common_google_play_services_unsupported_text = 2131099663;
			
			// aapt resource value: 0x7f06000e
			public const int common_google_play_services_unsupported_title = 2131099662;
			
			// aapt resource value: 0x7f060010
			public const int common_google_play_services_update_button = 2131099664;
			
			// aapt resource value: 0x7f060008
			public const int common_google_play_services_update_text = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int common_google_play_services_update_title = 2131099655;
			
			// aapt resource value: 0x7f060011
			public const int common_signin_button_text = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int common_signin_button_text_long = 2131099666;
			
			// aapt resource value: 0x7f06001c
			public const int menu_name = 2131099676;
			
			// aapt resource value: 0x7f06001d
			public const int quiz_instructions = 2131099677;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0a0005
			public const int ProgressBarDialog = 2131361797;
			
			// aapt resource value: 0x7f0a0003
			public const int TextAppearance_TabPageIndicator = 2131361795;
			
			// aapt resource value: 0x7f0a0000
			public const int Theme_PageIndicatorDefaults = 2131361792;
			
			// aapt resource value: 0x7f0a0006
			public const int Theme_Splash = 2131361798;
			
			// aapt resource value: 0x7f0a0001
			public const int Widget = 2131361793;
			
			// aapt resource value: 0x7f0a0004
			public const int Widget_IconPageIndicator = 2131361796;
			
			// aapt resource value: 0x7f0a0002
			public const int Widget_TabPageIndicator = 2131361794;
			
			// aapt resource value: 0x7f0a0008
			public const int button_lbk = 2131361800;
			
			// aapt resource value: 0x7f0a0007
			public const int main_content = 2131361799;
			
			// aapt resource value: 0x7f0a000d
			public const int quiz_answer = 2131361805;
			
			// aapt resource value: 0x7f0a000e
			public const int quiz_info1 = 2131361806;
			
			// aapt resource value: 0x7f0a000f
			public const int quiz_info2 = 2131361807;
			
			// aapt resource value: 0x7f0a000c
			public const int quiz_question = 2131361804;
			
			// aapt resource value: 0x7f0a000b
			public const int required_item = 2131361803;
			
			// aapt resource value: 0x7f0a000a
			public const int section_footer = 2131361802;
			
			// aapt resource value: 0x7f0a0009
			public const int section_header = 2131361801;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CirclePageIndicator = new int[] {
					16842948,
					16842964,
					2130771988,
					2130771990,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996};
			
			// aapt resource value: 1
			public const int CirclePageIndicator_android_background = 1;
			
			// aapt resource value: 0
			public const int CirclePageIndicator_android_orientation = 0;
			
			// aapt resource value: 2
			public const int CirclePageIndicator_centered = 2;
			
			// aapt resource value: 4
			public const int CirclePageIndicator_fillColor = 4;
			
			// aapt resource value: 5
			public const int CirclePageIndicator_pageColor = 5;
			
			// aapt resource value: 6
			public const int CirclePageIndicator_radius = 6;
			
			// aapt resource value: 7
			public const int CirclePageIndicator_snap = 7;
			
			// aapt resource value: 8
			public const int CirclePageIndicator_strokeColor = 8;
			
			// aapt resource value: 3
			public const int CirclePageIndicator_strokeWidth = 3;
			
			public static int[] DefaultImage = new int[] {
					2130772013};
			
			// aapt resource value: 0
			public const int DefaultImage_defaultImage = 0;
			
			public static int[] IsThumbnail = new int[] {
					2130772014};
			
			// aapt resource value: 0
			public const int IsThumbnail_thumbnail = 0;
			
			public static int[] LinePageIndicator = new int[] {
					16842964,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771997,
					2130771998};
			
			// aapt resource value: 0
			public const int LinePageIndicator_android_background = 0;
			
			// aapt resource value: 1
			public const int LinePageIndicator_centered = 1;
			
			// aapt resource value: 6
			public const int LinePageIndicator_gapWidth = 6;
			
			// aapt resource value: 5
			public const int LinePageIndicator_lineWidth = 5;
			
			// aapt resource value: 2
			public const int LinePageIndicator_selectedColor = 2;
			
			// aapt resource value: 3
			public const int LinePageIndicator_strokeWidth = 3;
			
			// aapt resource value: 4
			public const int LinePageIndicator_unselectedColor = 4;
			
			public static int[] MapAttrs = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981};
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 6
			public const int MapAttrs_uiCompass = 6;
			
			// aapt resource value: 7
			public const int MapAttrs_uiRotateGestures = 7;
			
			// aapt resource value: 8
			public const int MapAttrs_uiScrollGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiTiltGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiZoomControls = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomGestures = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_useViewLifecycle = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_zOrderOnTop = 13;
			
			public static int[] MvxBinding = new int[] {
					2130772015,
					2130772016};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130772017};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130772020};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130772018,
					2130772019};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			public static int[] TitlePageIndicator = new int[] {
					16842901,
					16842904,
					16842964,
					2130771989,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006,
					2130772007,
					2130772008,
					2130772009};
			
			// aapt resource value: 2
			public const int TitlePageIndicator_android_background = 2;
			
			// aapt resource value: 1
			public const int TitlePageIndicator_android_textColor = 1;
			
			// aapt resource value: 0
			public const int TitlePageIndicator_android_textSize = 0;
			
			// aapt resource value: 4
			public const int TitlePageIndicator_clipPadding = 4;
			
			// aapt resource value: 5
			public const int TitlePageIndicator_footerColor = 5;
			
			// aapt resource value: 8
			public const int TitlePageIndicator_footerIndicatorHeight = 8;
			
			// aapt resource value: 7
			public const int TitlePageIndicator_footerIndicatorStyle = 7;
			
			// aapt resource value: 9
			public const int TitlePageIndicator_footerIndicatorUnderlinePadding = 9;
			
			// aapt resource value: 6
			public const int TitlePageIndicator_footerLineHeight = 6;
			
			// aapt resource value: 10
			public const int TitlePageIndicator_footerPadding = 10;
			
			// aapt resource value: 11
			public const int TitlePageIndicator_linePosition = 11;
			
			// aapt resource value: 12
			public const int TitlePageIndicator_selectedBold = 12;
			
			// aapt resource value: 3
			public const int TitlePageIndicator_selectedColor = 3;
			
			// aapt resource value: 13
			public const int TitlePageIndicator_titlePadding = 13;
			
			// aapt resource value: 14
			public const int TitlePageIndicator_topPadding = 14;
			
			public static int[] UnderlinePageIndicator = new int[] {
					16842964,
					2130771989,
					2130772010,
					2130772011,
					2130772012};
			
			// aapt resource value: 0
			public const int UnderlinePageIndicator_android_background = 0;
			
			// aapt resource value: 3
			public const int UnderlinePageIndicator_fadeDelay = 3;
			
			// aapt resource value: 4
			public const int UnderlinePageIndicator_fadeLength = 4;
			
			// aapt resource value: 2
			public const int UnderlinePageIndicator_fades = 2;
			
			// aapt resource value: 1
			public const int UnderlinePageIndicator_selectedColor = 1;
			
			public static int[] ViewPagerIndicator = new int[] {
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987};
			
			// aapt resource value: 0
			public const int ViewPagerIndicator_vpiCirclePageIndicatorStyle = 0;
			
			// aapt resource value: 1
			public const int ViewPagerIndicator_vpiIconPageIndicatorStyle = 1;
			
			// aapt resource value: 2
			public const int ViewPagerIndicator_vpiLinePageIndicatorStyle = 2;
			
			// aapt resource value: 4
			public const int ViewPagerIndicator_vpiTabPageIndicatorStyle = 4;
			
			// aapt resource value: 3
			public const int ViewPagerIndicator_vpiTitlePageIndicatorStyle = 3;
			
			// aapt resource value: 5
			public const int ViewPagerIndicator_vpiUnderlinePageIndicatorStyle = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
