//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lbk.Mobile.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lbk.Mobile.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Internetverbindung.
        /// </summary>
        public static string Lbk_Error_NotReachable {
            get {
                return ResourceManager.GetString("Lbk.Error.NotReachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Fehler: .
        /// </summary>
        public static string Lbk_Error_OnAsyncExecute {
            get {
                return ResourceManager.GetString("Lbk.Error.OnAsyncExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hallo,
        ///
        ///also die kostenlose App vom Münchner Löwenbräukeller solltest Du Dir unbedingt mal anschauen.
        ///
        ///					http://itunes.apple.com/de/app/lowenbraukeller/id523578226
        ///
        ///					Da findest Du auch ein witziges Quiz, bei dem Du eine frische Maß Löwenbräu-Bier gewinnen kannst.
        ///
        ///					Servus, bis demnächst im Löwenbräukeller.
        /// </summary>
        public static string Lbk_HomeViewModel_Recommend_MailBody {
            get {
                return ResourceManager.GetString("Lbk.HomeViewModel.Recommend.MailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löwenbräukeller-App Empfelung.
        /// </summary>
        public static string Lbk_HomeViewModel_Recommend_MailSubject {
            get {
                return ResourceManager.GetString("Lbk.HomeViewModel.Recommend.MailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist eine eine neue Speisekarte gültig, die nun geladen werden kann..
        /// </summary>
        public static string Lbk_MenuViewModel_PdfDownloadQuestion {
            get {
                return ResourceManager.GetString("Lbk.MenuViewModel.PdfDownloadQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weiter.
        /// </summary>
        public static string Lbk_QuestionViewModel_Next {
            get {
                return ResourceManager.GetString("Lbk.QuestionViewModel.Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Richtig!.
        /// </summary>
        public static string Lbk_QuestionViewModel_Right {
            get {
                return ResourceManager.GetString("Lbk.QuestionViewModel.Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falsch!.
        /// </summary>
        public static string Lbk_QuestionViewModel_Wrong {
            get {
                return ResourceManager.GetString("Lbk.QuestionViewModel.Wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiermit bestätige ich, dass ich mindestens 18 Jahre alt bin..
        /// </summary>
        public static string Lbk_QuizStartViewModel_YouthProtectionQuestion {
            get {
                return ResourceManager.GetString("Lbk.QuizStartViewModel.YouthProtectionQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wollen Sie Quiz verlassen ?.
        /// </summary>
        public static string Lbk_QuizViewModel_AbortQuizQuestion {
            get {
                return ResourceManager.GetString("Lbk.QuizViewModel.AbortQuizQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Abbruchwunsch konnte nicht bestätigt werden..
        /// </summary>
        public static string Lbk_ReservationConfirmationViewModel_AbortReservationNotConfirmed {
            get {
                return ResourceManager.GetString("Lbk.ReservationConfirmationViewModel.AbortReservationNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wollen Sie die Reservierung abrechen?.
        /// </summary>
        public static string Lbk_ReservationConfirmationViewModel_AbortReservationQuestion {
            get {
                return ResourceManager.GetString("Lbk.ReservationConfirmationViewModel.AbortReservationQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Reservierung wurde nicht bestätigt..
        /// </summary>
        public static string Lbk_ReservationConfirmationViewModel_ReservationNotConfirmed {
            get {
                return ResourceManager.GetString("Lbk.ReservationConfirmationViewModel.ReservationNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beenden.
        /// </summary>
        public static string Lbk_Share_ButtonCancel {
            get {
                return ResourceManager.GetString("Lbk.Share.ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nein.
        /// </summary>
        public static string Lbk_Share_ButtonNo {
            get {
                return ResourceManager.GetString("Lbk.Share.ButtonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Lbk_Share_ButtonOk {
            get {
                return ResourceManager.GetString("Lbk.Share.ButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        public static string Lbk_Share_ButtonYes {
            get {
                return ResourceManager.GetString("Lbk.Share.ButtonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist ein Fehler beim Download aufgetreten..
        /// </summary>
        public static string Lbk_Share_DownloadError {
            get {
                return ResourceManager.GetString("Lbk.Share.DownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bis zum Ziel ca: {0}.
        /// </summary>
        public static string Lbk_Share_LocationDistance {
            get {
                return ResourceManager.GetString("Lbk.Share.LocationDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte versuchen Sie es später noch einmal..
        /// </summary>
        public static string Lbk_Share_PleaseTryNow {
            get {
                return ResourceManager.GetString("Lbk.Share.PleaseTryNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entschuldigung.
        /// </summary>
        public static string Lbk_Share_Sorry {
            get {
                return ResourceManager.GetString("Lbk.Share.Sorry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wollen Sie den Gutschein {0} jetzt aktivieren?.
        /// </summary>
        public static string Lbk_VoucherViewModel_ActivateVoucherQuestion {
            get {
                return ResourceManager.GetString("Lbk.VoucherViewModel.ActivateVoucherQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haben Sie den Gutschein jetzt eingelöst. Haben Sie ihr Getränk erhalten?.
        /// </summary>
        public static string Lbk_VoucherViewModel_UseVoucherQuestion {
            get {
                return ResourceManager.GetString("Lbk.VoucherViewModel.UseVoucherQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Den Gutschein {0} wurde erfolgreich aktiviert..
        /// </summary>
        public static string Lbk_VoucherViewModel_VoucherActvated {
            get {
                return ResourceManager.GetString("Lbk.VoucherViewModel.VoucherActvated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie haben Ihren Gutschein-Code {0} bereits bekommen..
        /// </summary>
        public static string Lbk_VoucherViewModel_VoucherAlreadyActvated {
            get {
                return ResourceManager.GetString("Lbk.VoucherViewModel.VoucherAlreadyActvated", resourceCulture);
            }
        }
    }
}
