//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lbk.Mobile.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lbk.Mobile.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet connection.
        /// </summary>
        public static string Lbk_Error_NotReachable {
            get {
                return ResourceManager.GetString("Lbk.Error.NotReachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Error: .
        /// </summary>
        public static string Lbk_Error_OnAsyncExecute {
            get {
                return ResourceManager.GetString("Lbk.Error.OnAsyncExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hallo,
        ///
        ///also die kostenlose App vom Münchner Löwenbräukeller solltest Du Dir unbedingt mal anschauen.
        ///
        ///					http://itunes.apple.com/de/app/lowenbraukeller/id523578226
        ///
        ///					Da findest Du auch ein witziges Quiz, bei dem Du eine frische Maß Löwenbräu-Bier gewinnen kannst.
        ///
        ///					Servus, bis demnächst im Löwenbräukeller.
        /// </summary>
        public static string Lbk_HomeViewModel_Recommend_MailBody {
            get {
                return ResourceManager.GetString("Lbk.HomeViewModel.Recommend.MailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löwenbräukeller-App Empfelung.
        /// </summary>
        public static string Lbk_HomeViewModel_Recommend_MailSubject {
            get {
                return ResourceManager.GetString("Lbk.HomeViewModel.Recommend.MailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is valid for a new menu, which can be downloaded now..
        /// </summary>
        public static string Lbk_MenuViewModel_PdfDownloadQuestion {
            get {
                return ResourceManager.GetString("Lbk.MenuViewModel.PdfDownloadQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Lbk_QuestionViewModel_Next {
            get {
                return ResourceManager.GetString("Lbk.QuestionViewModel.Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right!.
        /// </summary>
        public static string Lbk_QuestionViewModel_Right {
            get {
                return ResourceManager.GetString("Lbk.QuestionViewModel.Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong!.
        /// </summary>
        public static string Lbk_QuestionViewModel_Wrong {
            get {
                return ResourceManager.GetString("Lbk.QuestionViewModel.Wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations!.
        /// </summary>
        public static string Lbk_QuizNotSuccessResultViewModel_Congratulations {
            get {
                return ResourceManager.GetString("Lbk.QuizNotSuccessResultViewModel.Congratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I confirm that I am at least 18 years old..
        /// </summary>
        public static string Lbk_QuizStartViewModel_YouthProtectionQuestion {
            get {
                return ResourceManager.GetString("Lbk.QuizStartViewModel.YouthProtectionQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations!.
        /// </summary>
        public static string Lbk_QuizSuccessResultViewModel_Congratulations {
            get {
                return ResourceManager.GetString("Lbk.QuizSuccessResultViewModel.Congratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to leave quiz?.
        /// </summary>
        public static string Lbk_QuizViewModel_AbortQuizQuestion {
            get {
                return ResourceManager.GetString("Lbk.QuizViewModel.AbortQuizQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reaches {0} out of {1} points.
        /// </summary>
        public static string Lbk_QuizViewModel_CurrentPoints {
            get {
                return ResourceManager.GetString("Lbk.QuizViewModel.CurrentPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question {0} of {1}.
        /// </summary>
        public static string Lbk_QuizViewModel_CurrentQuestionNumber {
            get {
                return ResourceManager.GetString("Lbk.QuizViewModel.CurrentQuestionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cancellation request could not be confirmed..
        /// </summary>
        public static string Lbk_ReservationConfirmationViewModel_AbortReservationNotConfirmed {
            get {
                return ResourceManager.GetString("Lbk.ReservationConfirmationViewModel.AbortReservationNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to abort the reservation?.
        /// </summary>
        public static string Lbk_ReservationConfirmationViewModel_AbortReservationQuestion {
            get {
                return ResourceManager.GetString("Lbk.ReservationConfirmationViewModel.AbortReservationQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reservation is not confirmed..
        /// </summary>
        public static string Lbk_ReservationConfirmationViewModel_ReservationNotConfirmed {
            get {
                return ResourceManager.GetString("Lbk.ReservationConfirmationViewModel.ReservationNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reservation was canceled..
        /// </summary>
        public static string Lbk_ReservationResultViewModel_AbortedByCustomer {
            get {
                return ResourceManager.GetString("Lbk.ReservationResultViewModel.AbortedByCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liber guest, unfortunately we can not confirm your reservation request.
        ///Please call us at:
        ///089 54726690 an.
        ///Your Löwenbräukeler team..
        /// </summary>
        public static string Lbk_ReservationResultViewModel_DeclinedByRestaurant {
            get {
                return ResourceManager.GetString("Lbk.ReservationResultViewModel.DeclinedByRestaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Places are reserved.
        ///You still get a text message with the reservation data..
        /// </summary>
        public static string Lbk_ReservationResultViewModel_SuccessConfirmation {
            get {
                return ResourceManager.GetString("Lbk.ReservationResultViewModel.SuccessConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Lbk_Share_ButtonCancel {
            get {
                return ResourceManager.GetString("Lbk.Share.ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Lbk_Share_ButtonNo {
            get {
                return ResourceManager.GetString("Lbk.Share.ButtonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Lbk_Share_ButtonOk {
            get {
                return ResourceManager.GetString("Lbk.Share.ButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Lbk_Share_ButtonYes {
            get {
                return ResourceManager.GetString("Lbk.Share.ButtonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error during the download..
        /// </summary>
        public static string Lbk_Share_DownloadError {
            get {
                return ResourceManager.GetString("Lbk.Share.DownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To destination approx: {0}.
        /// </summary>
        public static string Lbk_Share_LocationDistance {
            get {
                return ResourceManager.GetString("Lbk.Share.LocationDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again later..
        /// </summary>
        public static string Lbk_Share_PleaseTryNow {
            get {
                return ResourceManager.GetString("Lbk.Share.PleaseTryNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already gotten your coupon code..
        /// </summary>
        public static string Lbk_Share_QuizAlreadyReceiveVoucher {
            get {
                return ResourceManager.GetString("Lbk.Share.QuizAlreadyReceiveVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately there is {0} right answer to a free beer voucher..
        /// </summary>
        public static string Lbk_Share_QuizMissingPoint {
            get {
                return ResourceManager.GetString("Lbk.Share.QuizMissingPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately, you are missing {0} correct answers to a free beer voucher..
        /// </summary>
        public static string Lbk_Share_QuizMissingPoints {
            get {
                return ResourceManager.GetString("Lbk.Share.QuizMissingPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached {0} of {1} points..
        /// </summary>
        public static string Lbk_Share_QuizResultPoints {
            get {
                return ResourceManager.GetString("Lbk.Share.QuizResultPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have won a free beer voucher..
        /// </summary>
        public static string Lbk_Share_QuizWinVoucher {
            get {
                return ResourceManager.GetString("Lbk.Share.QuizWinVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your coupon code:.
        /// </summary>
        public static string Lbk_Share_QuizYourCouponCode {
            get {
                return ResourceManager.GetString("Lbk.Share.QuizYourCouponCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry.
        /// </summary>
        public static string Lbk_Share_Sorry {
            get {
                return ResourceManager.GetString("Lbk.Share.Sorry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Lbk_Test_Text {
            get {
                return ResourceManager.GetString("Lbk.Test.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to activate the coupon {0} now?.
        /// </summary>
        public static string Lbk_VoucherListViewModel_ActivateVoucherQuestion {
            get {
                return ResourceManager.GetString("Lbk.VoucherListViewModel.ActivateVoucherQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You now have redeemed the voucher. Did you get their drink?.
        /// </summary>
        public static string Lbk_VoucherListViewModel_UseVoucherQuestion {
            get {
                return ResourceManager.GetString("Lbk.VoucherListViewModel.UseVoucherQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The voucher {0} has been successfully activated..
        /// </summary>
        public static string Lbk_VoucherListViewModel_VoucherActvated {
            get {
                return ResourceManager.GetString("Lbk.VoucherListViewModel.VoucherActvated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already gotten your coupon code {0}..
        /// </summary>
        public static string Lbk_VoucherListViewModel_VoucherAlreadyActvated {
            get {
                return ResourceManager.GetString("Lbk.VoucherListViewModel.VoucherAlreadyActvated", resourceCulture);
            }
        }
    }
}
