//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lbk.Mobile.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lbk.Mobile.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet connection.
        /// </summary>
        public static string Lbk_Error_NotReachable {
            get {
                return ResourceManager.GetString("Lbk.Error.NotReachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Error: .
        /// </summary>
        public static string Lbk_Error_OnAsyncExecute {
            get {
                return ResourceManager.GetString("Lbk.Error.OnAsyncExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Eng) Hallo ......
        /// </summary>
        public static string Lbk_HomeViewModel_Recommend_MailBody {
            get {
                return ResourceManager.GetString("Lbk.HomeViewModel.Recommend.MailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Eng) Löwenbräukeller-App Empfelung.
        /// </summary>
        public static string Lbk_HomeViewModel_Recommend_MailSubject {
            get {
                return ResourceManager.GetString("Lbk.HomeViewModel.Recommend.MailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Lbk_QuestionViewModel_Next {
            get {
                return ResourceManager.GetString("Lbk.QuestionViewModel.Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right!.
        /// </summary>
        public static string Lbk_QuestionViewModel_Right {
            get {
                return ResourceManager.GetString("Lbk.QuestionViewModel.Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong!.
        /// </summary>
        public static string Lbk_QuestionViewModel_Wrong {
            get {
                return ResourceManager.GetString("Lbk.QuestionViewModel.Wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I confirm that I am at least 18 years old..
        /// </summary>
        public static string Lbk_QuizStartViewModel_YouthProtectionQuestion {
            get {
                return ResourceManager.GetString("Lbk.QuizStartViewModel.YouthProtectionQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to leave quiz?.
        /// </summary>
        public static string Lbk_QuizViewModel_AbortQuizQuestion {
            get {
                return ResourceManager.GetString("Lbk.QuizViewModel.AbortQuizQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Lbk_Shared_ButtonCancelText {
            get {
                return ResourceManager.GetString("Lbk.Shared.ButtonCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Lbk_Shared_ButtonConfirmText {
            get {
                return ResourceManager.GetString("Lbk.Shared.ButtonConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Lbk_Test_Text {
            get {
                return ResourceManager.GetString("Lbk.Test.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to activate the coupon {0} now?.
        /// </summary>
        public static string Lbk_VoucherViewModel_ActivateVoucherQuestion {
            get {
                return ResourceManager.GetString("Lbk.VoucherViewModel.ActivateVoucherQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You now have redeemed the voucher. Did you get their drink?.
        /// </summary>
        public static string Lbk_VoucherViewModel_UseVoucherQuestion {
            get {
                return ResourceManager.GetString("Lbk.VoucherViewModel.UseVoucherQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The voucher {0} has been successfully activated..
        /// </summary>
        public static string Lbk_VoucherViewModel_VoucherActvated {
            get {
                return ResourceManager.GetString("Lbk.VoucherViewModel.VoucherActvated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already gotten your coupon code {0}..
        /// </summary>
        public static string Lbk_VoucherViewModel_VoucherAlreadyActvated {
            get {
                return ResourceManager.GetString("Lbk.VoucherViewModel.VoucherAlreadyActvated", resourceCulture);
            }
        }
    }
}
