//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceClient.Pcl.Hampel {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://liveviewing.hampel-auctions.com/", ConfigurationName="Hampel.ArticleWebServiceSoap")]
    public interface ArticleWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://liveviewing.hampel-auctions.com/getArtilce", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.IAsyncResult BegingetArtilce(System.AsyncCallback callback, object asyncState);
        
        ServiceClient.Pcl.Hampel.Article EndgetArtilce(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://liveviewing.hampel-auctions.com/getArtilceLng", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.IAsyncResult BegingetArtilceLng(string code, string culture, System.AsyncCallback callback, object asyncState);
        
        ServiceClient.Pcl.Hampel.Article EndgetArtilceLng(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://liveviewing.hampel-auctions.com/setArtilce", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.IAsyncResult BeginsetArtilce(double code, System.AsyncCallback callback, object asyncState);
        
        bool EndsetArtilce(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://liveviewing.hampel-auctions.com/setCurrentOffer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.IAsyncResult BeginsetCurrentOffer(ServiceClient.Pcl.Hampel.Offer cOffer, string key, System.AsyncCallback callback, object asyncState);
        
        bool EndsetCurrentOffer(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://liveviewing.hampel-auctions.com/getCurrentOffer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.IAsyncResult BegingetCurrentOffer(System.AsyncCallback callback, object asyncState);
        
        ServiceClient.Pcl.Hampel.Offer EndgetCurrentOffer(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://liveviewing.hampel-auctions.com/resetCurrentOffer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.IAsyncResult BeginresetCurrentOffer(string key, System.AsyncCallback callback, object asyncState);
        
        void EndresetCurrentOffer(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://liveviewing.hampel-auctions.com/setCurrentOffer2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.IAsyncResult BeginsetCurrentOffer2(double eur, double usd, double gbr, double rur, double jpy, System.AsyncCallback callback, object asyncState);
        
        void EndsetCurrentOffer2(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18054")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://liveviewing.hampel-auctions.com/")]
    public partial class Article : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double catalogNumberField;
        
        private double codeField;
        
        private string imageUrlField;
        
        private string headlineField;
        
        private string descriptionField;
        
        private string linkField;
        
        private string startPriceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double CatalogNumber {
            get {
                return this.catalogNumberField;
            }
            set {
                this.catalogNumberField = value;
                this.RaisePropertyChanged("CatalogNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ImageUrl {
            get {
                return this.imageUrlField;
            }
            set {
                this.imageUrlField = value;
                this.RaisePropertyChanged("ImageUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Headline {
            get {
                return this.headlineField;
            }
            set {
                this.headlineField = value;
                this.RaisePropertyChanged("Headline");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
                this.RaisePropertyChanged("Link");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string StartPrice {
            get {
                return this.startPriceField;
            }
            set {
                this.startPriceField = value;
                this.RaisePropertyChanged("StartPrice");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18054")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://liveviewing.hampel-auctions.com/")]
    public partial class Offer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double eURField;
        
        private double uSDField;
        
        private double jPYField;
        
        private double gBRField;
        
        private double rURField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double EUR {
            get {
                return this.eURField;
            }
            set {
                this.eURField = value;
                this.RaisePropertyChanged("EUR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double USD {
            get {
                return this.uSDField;
            }
            set {
                this.uSDField = value;
                this.RaisePropertyChanged("USD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double JPY {
            get {
                return this.jPYField;
            }
            set {
                this.jPYField = value;
                this.RaisePropertyChanged("JPY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double GBR {
            get {
                return this.gBRField;
            }
            set {
                this.gBRField = value;
                this.RaisePropertyChanged("GBR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public double RUR {
            get {
                return this.rURField;
            }
            set {
                this.rURField = value;
                this.RaisePropertyChanged("RUR");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ArticleWebServiceSoapChannel : ServiceClient.Pcl.Hampel.ArticleWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getArtilceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getArtilceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ServiceClient.Pcl.Hampel.Article Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ServiceClient.Pcl.Hampel.Article)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getArtilceLngCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getArtilceLngCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ServiceClient.Pcl.Hampel.Article Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ServiceClient.Pcl.Hampel.Article)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class setArtilceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public setArtilceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class setCurrentOfferCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public setCurrentOfferCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getCurrentOfferCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getCurrentOfferCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ServiceClient.Pcl.Hampel.Offer Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ServiceClient.Pcl.Hampel.Offer)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ArticleWebServiceSoapClient : System.ServiceModel.ClientBase<ServiceClient.Pcl.Hampel.ArticleWebServiceSoap>, ServiceClient.Pcl.Hampel.ArticleWebServiceSoap {
        
        private BeginOperationDelegate onBegingetArtilceDelegate;
        
        private EndOperationDelegate onEndgetArtilceDelegate;
        
        private System.Threading.SendOrPostCallback ongetArtilceCompletedDelegate;
        
        private BeginOperationDelegate onBegingetArtilceLngDelegate;
        
        private EndOperationDelegate onEndgetArtilceLngDelegate;
        
        private System.Threading.SendOrPostCallback ongetArtilceLngCompletedDelegate;
        
        private BeginOperationDelegate onBeginsetArtilceDelegate;
        
        private EndOperationDelegate onEndsetArtilceDelegate;
        
        private System.Threading.SendOrPostCallback onsetArtilceCompletedDelegate;
        
        private BeginOperationDelegate onBeginsetCurrentOfferDelegate;
        
        private EndOperationDelegate onEndsetCurrentOfferDelegate;
        
        private System.Threading.SendOrPostCallback onsetCurrentOfferCompletedDelegate;
        
        private BeginOperationDelegate onBegingetCurrentOfferDelegate;
        
        private EndOperationDelegate onEndgetCurrentOfferDelegate;
        
        private System.Threading.SendOrPostCallback ongetCurrentOfferCompletedDelegate;
        
        private BeginOperationDelegate onBeginresetCurrentOfferDelegate;
        
        private EndOperationDelegate onEndresetCurrentOfferDelegate;
        
        private System.Threading.SendOrPostCallback onresetCurrentOfferCompletedDelegate;
        
        private BeginOperationDelegate onBeginsetCurrentOffer2Delegate;
        
        private EndOperationDelegate onEndsetCurrentOffer2Delegate;
        
        private System.Threading.SendOrPostCallback onsetCurrentOffer2CompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ArticleWebServiceSoapClient() : 
                base(ArticleWebServiceSoapClient.GetDefaultBinding(), ArticleWebServiceSoapClient.GetDefaultEndpointAddress()) {
        }
        
        public ArticleWebServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ArticleWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), ArticleWebServiceSoapClient.GetEndpointAddress(endpointConfiguration)) {
        }
        
        public ArticleWebServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ArticleWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
        }
        
        public ArticleWebServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ArticleWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
        }
        
        public ArticleWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<getArtilceCompletedEventArgs> getArtilceCompleted;
        
        public event System.EventHandler<getArtilceLngCompletedEventArgs> getArtilceLngCompleted;
        
        public event System.EventHandler<setArtilceCompletedEventArgs> setArtilceCompleted;
        
        public event System.EventHandler<setCurrentOfferCompletedEventArgs> setCurrentOfferCompleted;
        
        public event System.EventHandler<getCurrentOfferCompletedEventArgs> getCurrentOfferCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> resetCurrentOfferCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> setCurrentOffer2Completed;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ServiceClient.Pcl.Hampel.ArticleWebServiceSoap.BegingetArtilce(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetArtilce(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceClient.Pcl.Hampel.Article ServiceClient.Pcl.Hampel.ArticleWebServiceSoap.EndgetArtilce(System.IAsyncResult result) {
            return base.Channel.EndgetArtilce(result);
        }
        
        private System.IAsyncResult OnBegingetArtilce(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((ServiceClient.Pcl.Hampel.ArticleWebServiceSoap)(this)).BegingetArtilce(callback, asyncState);
        }
        
        private object[] OnEndgetArtilce(System.IAsyncResult result) {
            ServiceClient.Pcl.Hampel.Article retVal = ((ServiceClient.Pcl.Hampel.ArticleWebServiceSoap)(this)).EndgetArtilce(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetArtilceCompleted(object state) {
            if ((this.getArtilceCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getArtilceCompleted(this, new getArtilceCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getArtilceAsync() {
            this.getArtilceAsync(null);
        }
        
        public void getArtilceAsync(object userState) {
            if ((this.onBegingetArtilceDelegate == null)) {
                this.onBegingetArtilceDelegate = new BeginOperationDelegate(this.OnBegingetArtilce);
            }
            if ((this.onEndgetArtilceDelegate == null)) {
                this.onEndgetArtilceDelegate = new EndOperationDelegate(this.OnEndgetArtilce);
            }
            if ((this.ongetArtilceCompletedDelegate == null)) {
                this.ongetArtilceCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetArtilceCompleted);
            }
            base.InvokeAsync(this.onBegingetArtilceDelegate, null, this.onEndgetArtilceDelegate, this.ongetArtilceCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ServiceClient.Pcl.Hampel.ArticleWebServiceSoap.BegingetArtilceLng(string code, string culture, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetArtilceLng(code, culture, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceClient.Pcl.Hampel.Article ServiceClient.Pcl.Hampel.ArticleWebServiceSoap.EndgetArtilceLng(System.IAsyncResult result) {
            return base.Channel.EndgetArtilceLng(result);
        }
        
        private System.IAsyncResult OnBegingetArtilceLng(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string code = ((string)(inValues[0]));
            string culture = ((string)(inValues[1]));
            return ((ServiceClient.Pcl.Hampel.ArticleWebServiceSoap)(this)).BegingetArtilceLng(code, culture, callback, asyncState);
        }
        
        private object[] OnEndgetArtilceLng(System.IAsyncResult result) {
            ServiceClient.Pcl.Hampel.Article retVal = ((ServiceClient.Pcl.Hampel.ArticleWebServiceSoap)(this)).EndgetArtilceLng(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetArtilceLngCompleted(object state) {
            if ((this.getArtilceLngCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getArtilceLngCompleted(this, new getArtilceLngCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getArtilceLngAsync(string code, string culture) {
            this.getArtilceLngAsync(code, culture, null);
        }
        
        public void getArtilceLngAsync(string code, string culture, object userState) {
            if ((this.onBegingetArtilceLngDelegate == null)) {
                this.onBegingetArtilceLngDelegate = new BeginOperationDelegate(this.OnBegingetArtilceLng);
            }
            if ((this.onEndgetArtilceLngDelegate == null)) {
                this.onEndgetArtilceLngDelegate = new EndOperationDelegate(this.OnEndgetArtilceLng);
            }
            if ((this.ongetArtilceLngCompletedDelegate == null)) {
                this.ongetArtilceLngCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetArtilceLngCompleted);
            }
            base.InvokeAsync(this.onBegingetArtilceLngDelegate, new object[] {
                        code,
                        culture}, this.onEndgetArtilceLngDelegate, this.ongetArtilceLngCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ServiceClient.Pcl.Hampel.ArticleWebServiceSoap.BeginsetArtilce(double code, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginsetArtilce(code, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool ServiceClient.Pcl.Hampel.ArticleWebServiceSoap.EndsetArtilce(System.IAsyncResult result) {
            return base.Channel.EndsetArtilce(result);
        }
        
        private System.IAsyncResult OnBeginsetArtilce(object[] inValues, System.AsyncCallback callback, object asyncState) {
            double code = ((double)(inValues[0]));
            return ((ServiceClient.Pcl.Hampel.ArticleWebServiceSoap)(this)).BeginsetArtilce(code, callback, asyncState);
        }
        
        private object[] OnEndsetArtilce(System.IAsyncResult result) {
            bool retVal = ((ServiceClient.Pcl.Hampel.ArticleWebServiceSoap)(this)).EndsetArtilce(result);
            return new object[] {
                    retVal};
        }
        
        private void OnsetArtilceCompleted(object state) {
            if ((this.setArtilceCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.setArtilceCompleted(this, new setArtilceCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void setArtilceAsync(double code) {
            this.setArtilceAsync(code, null);
        }
        
        public void setArtilceAsync(double code, object userState) {
            if ((this.onBeginsetArtilceDelegate == null)) {
                this.onBeginsetArtilceDelegate = new BeginOperationDelegate(this.OnBeginsetArtilce);
            }
            if ((this.onEndsetArtilceDelegate == null)) {
                this.onEndsetArtilceDelegate = new EndOperationDelegate(this.OnEndsetArtilce);
            }
            if ((this.onsetArtilceCompletedDelegate == null)) {
                this.onsetArtilceCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnsetArtilceCompleted);
            }
            base.InvokeAsync(this.onBeginsetArtilceDelegate, new object[] {
                        code}, this.onEndsetArtilceDelegate, this.onsetArtilceCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ServiceClient.Pcl.Hampel.ArticleWebServiceSoap.BeginsetCurrentOffer(ServiceClient.Pcl.Hampel.Offer cOffer, string key, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginsetCurrentOffer(cOffer, key, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool ServiceClient.Pcl.Hampel.ArticleWebServiceSoap.EndsetCurrentOffer(System.IAsyncResult result) {
            return base.Channel.EndsetCurrentOffer(result);
        }
        
        private System.IAsyncResult OnBeginsetCurrentOffer(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ServiceClient.Pcl.Hampel.Offer cOffer = ((ServiceClient.Pcl.Hampel.Offer)(inValues[0]));
            string key = ((string)(inValues[1]));
            return ((ServiceClient.Pcl.Hampel.ArticleWebServiceSoap)(this)).BeginsetCurrentOffer(cOffer, key, callback, asyncState);
        }
        
        private object[] OnEndsetCurrentOffer(System.IAsyncResult result) {
            bool retVal = ((ServiceClient.Pcl.Hampel.ArticleWebServiceSoap)(this)).EndsetCurrentOffer(result);
            return new object[] {
                    retVal};
        }
        
        private void OnsetCurrentOfferCompleted(object state) {
            if ((this.setCurrentOfferCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.setCurrentOfferCompleted(this, new setCurrentOfferCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void setCurrentOfferAsync(ServiceClient.Pcl.Hampel.Offer cOffer, string key) {
            this.setCurrentOfferAsync(cOffer, key, null);
        }
        
        public void setCurrentOfferAsync(ServiceClient.Pcl.Hampel.Offer cOffer, string key, object userState) {
            if ((this.onBeginsetCurrentOfferDelegate == null)) {
                this.onBeginsetCurrentOfferDelegate = new BeginOperationDelegate(this.OnBeginsetCurrentOffer);
            }
            if ((this.onEndsetCurrentOfferDelegate == null)) {
                this.onEndsetCurrentOfferDelegate = new EndOperationDelegate(this.OnEndsetCurrentOffer);
            }
            if ((this.onsetCurrentOfferCompletedDelegate == null)) {
                this.onsetCurrentOfferCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnsetCurrentOfferCompleted);
            }
            base.InvokeAsync(this.onBeginsetCurrentOfferDelegate, new object[] {
                        cOffer,
                        key}, this.onEndsetCurrentOfferDelegate, this.onsetCurrentOfferCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ServiceClient.Pcl.Hampel.ArticleWebServiceSoap.BegingetCurrentOffer(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetCurrentOffer(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceClient.Pcl.Hampel.Offer ServiceClient.Pcl.Hampel.ArticleWebServiceSoap.EndgetCurrentOffer(System.IAsyncResult result) {
            return base.Channel.EndgetCurrentOffer(result);
        }
        
        private System.IAsyncResult OnBegingetCurrentOffer(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((ServiceClient.Pcl.Hampel.ArticleWebServiceSoap)(this)).BegingetCurrentOffer(callback, asyncState);
        }
        
        private object[] OnEndgetCurrentOffer(System.IAsyncResult result) {
            ServiceClient.Pcl.Hampel.Offer retVal = ((ServiceClient.Pcl.Hampel.ArticleWebServiceSoap)(this)).EndgetCurrentOffer(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetCurrentOfferCompleted(object state) {
            if ((this.getCurrentOfferCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getCurrentOfferCompleted(this, new getCurrentOfferCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getCurrentOfferAsync() {
            this.getCurrentOfferAsync(null);
        }
        
        public void getCurrentOfferAsync(object userState) {
            if ((this.onBegingetCurrentOfferDelegate == null)) {
                this.onBegingetCurrentOfferDelegate = new BeginOperationDelegate(this.OnBegingetCurrentOffer);
            }
            if ((this.onEndgetCurrentOfferDelegate == null)) {
                this.onEndgetCurrentOfferDelegate = new EndOperationDelegate(this.OnEndgetCurrentOffer);
            }
            if ((this.ongetCurrentOfferCompletedDelegate == null)) {
                this.ongetCurrentOfferCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetCurrentOfferCompleted);
            }
            base.InvokeAsync(this.onBegingetCurrentOfferDelegate, null, this.onEndgetCurrentOfferDelegate, this.ongetCurrentOfferCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ServiceClient.Pcl.Hampel.ArticleWebServiceSoap.BeginresetCurrentOffer(string key, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginresetCurrentOffer(key, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void ServiceClient.Pcl.Hampel.ArticleWebServiceSoap.EndresetCurrentOffer(System.IAsyncResult result) {
            base.Channel.EndresetCurrentOffer(result);
        }
        
        private System.IAsyncResult OnBeginresetCurrentOffer(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string key = ((string)(inValues[0]));
            return ((ServiceClient.Pcl.Hampel.ArticleWebServiceSoap)(this)).BeginresetCurrentOffer(key, callback, asyncState);
        }
        
        private object[] OnEndresetCurrentOffer(System.IAsyncResult result) {
            ((ServiceClient.Pcl.Hampel.ArticleWebServiceSoap)(this)).EndresetCurrentOffer(result);
            return null;
        }
        
        private void OnresetCurrentOfferCompleted(object state) {
            if ((this.resetCurrentOfferCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.resetCurrentOfferCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void resetCurrentOfferAsync(string key) {
            this.resetCurrentOfferAsync(key, null);
        }
        
        public void resetCurrentOfferAsync(string key, object userState) {
            if ((this.onBeginresetCurrentOfferDelegate == null)) {
                this.onBeginresetCurrentOfferDelegate = new BeginOperationDelegate(this.OnBeginresetCurrentOffer);
            }
            if ((this.onEndresetCurrentOfferDelegate == null)) {
                this.onEndresetCurrentOfferDelegate = new EndOperationDelegate(this.OnEndresetCurrentOffer);
            }
            if ((this.onresetCurrentOfferCompletedDelegate == null)) {
                this.onresetCurrentOfferCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnresetCurrentOfferCompleted);
            }
            base.InvokeAsync(this.onBeginresetCurrentOfferDelegate, new object[] {
                        key}, this.onEndresetCurrentOfferDelegate, this.onresetCurrentOfferCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ServiceClient.Pcl.Hampel.ArticleWebServiceSoap.BeginsetCurrentOffer2(double eur, double usd, double gbr, double rur, double jpy, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginsetCurrentOffer2(eur, usd, gbr, rur, jpy, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void ServiceClient.Pcl.Hampel.ArticleWebServiceSoap.EndsetCurrentOffer2(System.IAsyncResult result) {
            base.Channel.EndsetCurrentOffer2(result);
        }
        
        private System.IAsyncResult OnBeginsetCurrentOffer2(object[] inValues, System.AsyncCallback callback, object asyncState) {
            double eur = ((double)(inValues[0]));
            double usd = ((double)(inValues[1]));
            double gbr = ((double)(inValues[2]));
            double rur = ((double)(inValues[3]));
            double jpy = ((double)(inValues[4]));
            return ((ServiceClient.Pcl.Hampel.ArticleWebServiceSoap)(this)).BeginsetCurrentOffer2(eur, usd, gbr, rur, jpy, callback, asyncState);
        }
        
        private object[] OnEndsetCurrentOffer2(System.IAsyncResult result) {
            ((ServiceClient.Pcl.Hampel.ArticleWebServiceSoap)(this)).EndsetCurrentOffer2(result);
            return null;
        }
        
        private void OnsetCurrentOffer2Completed(object state) {
            if ((this.setCurrentOffer2Completed != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.setCurrentOffer2Completed(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void setCurrentOffer2Async(double eur, double usd, double gbr, double rur, double jpy) {
            this.setCurrentOffer2Async(eur, usd, gbr, rur, jpy, null);
        }
        
        public void setCurrentOffer2Async(double eur, double usd, double gbr, double rur, double jpy, object userState) {
            if ((this.onBeginsetCurrentOffer2Delegate == null)) {
                this.onBeginsetCurrentOffer2Delegate = new BeginOperationDelegate(this.OnBeginsetCurrentOffer2);
            }
            if ((this.onEndsetCurrentOffer2Delegate == null)) {
                this.onEndsetCurrentOffer2Delegate = new EndOperationDelegate(this.OnEndsetCurrentOffer2);
            }
            if ((this.onsetCurrentOffer2CompletedDelegate == null)) {
                this.onsetCurrentOffer2CompletedDelegate = new System.Threading.SendOrPostCallback(this.OnsetCurrentOffer2Completed);
            }
            base.InvokeAsync(this.onBeginsetCurrentOffer2Delegate, new object[] {
                        eur,
                        usd,
                        gbr,
                        rur,
                        jpy}, this.onEndsetCurrentOffer2Delegate, this.onsetCurrentOffer2CompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override ServiceClient.Pcl.Hampel.ArticleWebServiceSoap CreateChannel() {
            return new ArticleWebServiceSoapClientChannel(this);
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.ArticleWebServiceSoap)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.MaxReceivedMessageSize = int.MaxValue;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.ArticleWebServiceSoap)) {
                return new System.ServiceModel.EndpointAddress("http://liveviewing.hampel-auctions.com/articlewebservice.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return ArticleWebServiceSoapClient.GetBindingForEndpoint(EndpointConfiguration.ArticleWebServiceSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return ArticleWebServiceSoapClient.GetEndpointAddress(EndpointConfiguration.ArticleWebServiceSoap);
        }
        
        private class ArticleWebServiceSoapClientChannel : ChannelBase<ServiceClient.Pcl.Hampel.ArticleWebServiceSoap>, ServiceClient.Pcl.Hampel.ArticleWebServiceSoap {
            
            public ArticleWebServiceSoapClientChannel(System.ServiceModel.ClientBase<ServiceClient.Pcl.Hampel.ArticleWebServiceSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BegingetArtilce(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("getArtilce", _args, callback, asyncState);
                return _result;
            }
            
            public ServiceClient.Pcl.Hampel.Article EndgetArtilce(System.IAsyncResult result) {
                object[] _args = new object[0];
                ServiceClient.Pcl.Hampel.Article _result = ((ServiceClient.Pcl.Hampel.Article)(base.EndInvoke("getArtilce", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetArtilceLng(string code, string culture, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = code;
                _args[1] = culture;
                System.IAsyncResult _result = base.BeginInvoke("getArtilceLng", _args, callback, asyncState);
                return _result;
            }
            
            public ServiceClient.Pcl.Hampel.Article EndgetArtilceLng(System.IAsyncResult result) {
                object[] _args = new object[0];
                ServiceClient.Pcl.Hampel.Article _result = ((ServiceClient.Pcl.Hampel.Article)(base.EndInvoke("getArtilceLng", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginsetArtilce(double code, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = code;
                System.IAsyncResult _result = base.BeginInvoke("setArtilce", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndsetArtilce(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("setArtilce", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginsetCurrentOffer(ServiceClient.Pcl.Hampel.Offer cOffer, string key, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = cOffer;
                _args[1] = key;
                System.IAsyncResult _result = base.BeginInvoke("setCurrentOffer", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndsetCurrentOffer(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("setCurrentOffer", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetCurrentOffer(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("getCurrentOffer", _args, callback, asyncState);
                return _result;
            }
            
            public ServiceClient.Pcl.Hampel.Offer EndgetCurrentOffer(System.IAsyncResult result) {
                object[] _args = new object[0];
                ServiceClient.Pcl.Hampel.Offer _result = ((ServiceClient.Pcl.Hampel.Offer)(base.EndInvoke("getCurrentOffer", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginresetCurrentOffer(string key, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = key;
                System.IAsyncResult _result = base.BeginInvoke("resetCurrentOffer", _args, callback, asyncState);
                return _result;
            }
            
            public void EndresetCurrentOffer(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("resetCurrentOffer", _args, result);
            }
            
            public System.IAsyncResult BeginsetCurrentOffer2(double eur, double usd, double gbr, double rur, double jpy, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[5];
                _args[0] = eur;
                _args[1] = usd;
                _args[2] = gbr;
                _args[3] = rur;
                _args[4] = jpy;
                System.IAsyncResult _result = base.BeginInvoke("setCurrentOffer2", _args, callback, asyncState);
                return _result;
            }
            
            public void EndsetCurrentOffer2(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("setCurrentOffer2", _args, result);
            }
        }
        
        public enum EndpointConfiguration {
            
            ArticleWebServiceSoap,
        }
    }
}
